---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: anime-secrets
  namespace: anime-v2
spec:
  secretTemplates:
    - name: registry-credentials
      type: kubernetes.io/dockerconfigjson
      stringData:
        .dockerconfigjson: ENC[AES256_GCM,data:pZKLKqnXfhcxhjBPqf7eMyA1kP0UyKUkteVJJwqU7Uxoze+XUEc1j7VW/B1MWRdD8c9CkIE/UzKFRDKzp+oGMKsxI5cKx9UHfEa31lJeW38Rz8PREWTBdy6msXrVx7yx7lYd8F1Y4ar0dSP/sbtWMaqytlw/8X/g4Ox2862TmgR+7+1S3Bl8z8rJNJcEepcT7JQrYbNTNEUjcUb7LPEi/DLHbSICvUWQmqly,iv:jdpNhgKcLRpbPxnqaxLWUS9n0PcWt49IY43hKQQ9McM=,tag:YJVr5HzLVKT4BRaHfBmGVw==,type:str]
    - name: s3-secrets
      stringData:
        REGION: ENC[AES256_GCM,data:xkAqnANVZQ==,iv:Qp/7a95eqH2zVbLnnmN5/QC5xxdx91vmkBrzCq+3HeU=,tag:GTQQidswOIdubg70/ogbaQ==,type:str]
        ACCESS_KEY: ENC[AES256_GCM,data:Uo6fuQOmOnLY0gwKZ4CTU0bdd9NsX9CmS7s=,iv:IVZTYrr31BXTLt2p6jSrj7Ys4MZqa3tpx4g8WE1wy9w=,tag:bBswp96N9g99RSUr59nCwA==,type:str]
        SECRET_KEY: ENC[AES256_GCM,data:Jj4GYo3rdelFhDQV8SJ76h4aRO8xO7e99X9yWl7H5+z0iZOV6yjmOkPsocDasxnHMcxTXht84EgmjXYnQLs8mw==,iv:IwkY+9sG61t8QoU3V03IgsxZltlV26bvtc5lJXqSnmE=,tag:FHJi11F6sC16RbiyOFwqvg==,type:str]
    - name: anime-secrets
      stringData:
        AUTH__SECRET: ENC[AES256_GCM,data:P4bbeC5yjpACAnN6eMSpMQIRqbu8yhznLb5Y7iNKZ6Y+ZnxcuMmoc+ZJS02a6M4xspLOtuJ7TD6rGWaVuEwE9w==,iv:+My3F3a2bn3BLcw+DV0YjhG3Z6FGafEUtGsJ4DMoX3A=,tag:+9TR4H4VNlNFVkIfjYABkg==,type:str]
        AUTH__OIDC__CLIENT_SECRET: ENC[AES256_GCM,data:pQcH7uSrO7pIAm3fREDk7yc7P3ZxyGT8u+Wkg7wMnMQin5G5yEqd56c3mva1QG52OCuX2ZE9Fc+st7BJqcZKqdO5mxDYlPdu,iv:se6lPIxw4Kt7fZncWX6MdlQe62cQeFBgczy1yXSMtBI=,tag:oiZ3Wt+7vcSk99tqvx8vjw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiZnJicmlyVU5JZm1LZm0x
        MEh6VVpiNGR0eFJ6WVFXZEo3SFI3Rk1hVXdzCjNBVjNsOGlFNGY4VTBqWDFXOEti
        SE4rdFU5QzVTSHJPczNuY0ZHNy9HT1EKLS0tIC94M0FrZzRvc3oxR0prVUVyMzNn
        WlhmdFBucVVtSWpjQU9PT1F6eE01bFUKzIxacGDU0qCycV94SrYGxgZAP4oVUffn
        XvPDZkC3+tS0ONnpbc2z3yMN0qLlofTaH+t42ae1XprBw9chwSm2VQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ff26etr9n8nsp2ve2lkh7w4dqd9g9m9u3y8aw77ureu639mrfatqmuqnhv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-13T15:08:05Z"
  mac: ENC[AES256_GCM,data:J8uSNS7PygPFUgK47kLc51icFfRPuOqOyqVwGR3Z0qwYU9yV4nawZPC2Ze8EuO2MNZ1nmRUWubFaFnZ9oSEUsp39HJOUBQGNLlu4oCtdUnxWPmmrbsBAocKk+R8p+C+FGJzclV/cxhJUfPIjfhPUCvSAPRgCQx9c/bsztBXjlO4=,iv:FHR0SQeIlfezyE9FLwf3ZdtRUwy9uZi+NfDvc3NVpNo=,tag:qRFGcTYK67hDEkO0d/J0zQ==,type:str]
  version: 3.13.0
