---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: anime-secrets
  namespace: anime-v2
spec:
  secretTemplates:
    - name: registry-credentials
      type: kubernetes.io/dockerconfigjson
      stringData:
        .dockerconfigjson: ENC[AES256_GCM,data:mvwMrCIA6ZYskZULdM63YHIen45nalOgVkqmQDDQ+knBDjv45aoFA9tjUliul7n2rbONLPwnZNrKmw3dy6xYXgHlLYRrMfqz4FytrfGb+csBFujoSLszfm6SdWdOS85MFPr1rT6l+E9xhjgAuFXUtlhQpjbxQ383IS4tyTSNu8BEKGqIZ+XXLQvYUd3OC+cRTqeAKSpcoB3obcQK5aLt3traSsq+ZeSzB5vp,iv:FNbBT4fm3rN0rKl/Ee0+9149CVzttqW7lY/UuHld0EQ=,tag:fe7hZ+FJouKX8l4TwkvMOg==,type:str]
    - name: anime-secrets
      stringData:
        AUTH__SECRET: ENC[AES256_GCM,data:vJ4RKwtBGH/Ft6dwjOk2npHJ+YPkjd9h8umXHsYAAgA/JtnX5o5kBGGaSrSeR1YOe6OnCXeUIUcWJJUcpQZacw==,iv:q1Jmg3bq4xdMRcVAPMyK8Uf3dnRPxwUIkvo992OAyZY=,tag:7n+RnZSXOER032FsJoNDIg==,type:str]
        AUTH__OIDC__CLIENT_SECRET: ENC[AES256_GCM,data:72+qTuxaCH/hg3nk/FLNPe/x+HXFGtZ5+8F8oAD+gilSuQuP43IEcQ54qkq+Ajrs73uacyijliW6xIX7bgLI9Eh2+6ywRJQL,iv:LqX5LVksKt4/oA+OhYQuLzDr9XZ2GgrVJOjuK1tJ4HU=,tag:A0WqaF0PPMbD2ejPjstCcg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKNnV2QXErNDJSem9OeEFq
        S2MzbVh2eS8yUkwrMnhac1NjOUFRTnliazFzCm9DUTNGSXVEZHlsU3VGNUhLcThN
        Z3pMMnBUTzBqaFhPelpoUzlkWnhuS28KLS0tIE9TUWpzajUyZlljTGRQV2lmeFNy
        NnlYSHlmQWwzRWxqaSsxVGh1M2YyVlUKF6KpK4JXIYxwUjnJ6LUfevovbbtRXlDe
        psJxS/V3D8Y/R3o9utxlusRaT2lZemIBybNdNy1+QScCkBWR1F+ndg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ff26etr9n8nsp2ve2lkh7w4dqd9g9m9u3y8aw77ureu639mrfatqmuqnhv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-06T10:23:55Z"
  mac: ENC[AES256_GCM,data:cp7N64F7njcd6p0uhE4BIoNY1IUgjybmE4A43I9PKhgt8pHaq38tbq7pR+mvV1wjQ7eoLcO5Ufaxft8VK7h8knlrBToQYC4kQJOV1B4cG/RPr6HrXua+P4yBqsL3CaXNjmaAFUGm1gOPmN6HD1FpuJUwDkpAEiAPpn/3QyBM8nE=,iv:LlyhZgSMrwoIXJ1h697tzR2ThpUTJyGFcsvUW06N1Yc=,tag:8UuJVsLQca5cFv1wO8nuaQ==,type:str]
  version: 3.13.3
