---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: anime-secrets
  namespace: anime-v2
spec:
  secretTemplates:
    - name: registry-credentials
      type: kubernetes.io/dockerconfigjson
      stringData:
        .dockerconfigjson: ENC[AES256_GCM,data:28iYmz2O98pvImMqCV4Q1DB/ITXX5DI7lak+2EuPO7Jm4PJV96hJorL4RBCTySGTXDf83Y/172a7hyBpLFcH4mTUwcP6a5YW1NB++swuVTg0xxf6MFITEPkyLHDNTZtDoQTWddxVNVReCrWSWap8miau41yg6+ra4GHxzTPwUEBGAFfNbhjCcImg0jkQuiTCluvqMcdzv8TF0TlYCVV4SK64HeRODo8kignC,iv:D5xJLo7SP7YoX3rAc2t9eaq1D6x3gWbNeP2eEkH99NY=,tag:OFAR5UCMvqRM3dXmQDInWQ==,type:str]
    - name: anime-secrets
      stringData:
        AUTH__SECRET: ENC[AES256_GCM,data:Pa1V7aJNiFEZ7j1pQGFwIAyROm4TAxXWjuMwF5bq69aZNyvd+1YlZRcvQg76TrQwB/7KcnjjmNP1D3zVZzka,iv:4slcH0ujR/wxOP2LQ+b6quDG4e+gJMtb27AAdsO5GA4=,tag:qMGereyx2F1adKG/pl2S+g==,type:str]
        AUTH__OIDC__CLIENT_SECRET: ENC[AES256_GCM,data:ndjxyuXgX9DXi5QwRdcj6xMuajni9v39l6sDX1/GueeY4LVCuVz2pQhS1Bh94NF3YXioD5jqWqc74s5wS6MLg/Y8om9N0gYgcy0kaFA9vuf5FtGi44GiGlU+rDtjENoYfStciPPXL8tOH3ILzzDytSmiPuMbVoolfoDcxGxv8JQ=,iv:kmncrgDtGsaXQAebIJSquvxAVqZpIR5nWKlLQbKAeWQ=,tag:Gh4OJx7VypP9Lw9+hIkrgw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0eTlEcjZiMlN0alpTeGlt
        SkpZajhOeHlDQkMzbkpkRU9Cd3ppSmNrOWswCnVqZ2ZJZS9rREhSS1JuV3hZWFI3
        NGNnTFZVbHpKWFpMN0VPL3NTQWt0NTAKLS0tIEFOYXNUY2FFZWlieFpTUnBJVUwv
        RzlHL1FVV0p3bTZIcTRaV2FtNHVYTUEKvOv4dYQebaTpYChWcTgvDolFcXU7fgR1
        T2kBo5SvZ8RclJkrOmuP+dPWZ/M5rKAx967hIjRKQ/u2lCppC9XEjA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ff26etr9n8nsp2ve2lkh7w4dqd9g9m9u3y8aw77ureu639mrfatqmuqnhv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-29T13:47:54Z"
  mac: ENC[AES256_GCM,data:pKXk2fgTW5Pn1GsU6BSMklkDMHl7E6TLVV7IA7E6Pm8WiB9mgWI02jktPXbQRKRIsz8dW44Mguh95klwI0q4+hkUPZNk2YhnxEDNSH7kvtxM6UrknU63EDHYnydivUcRu/eynGIKBx9ESF8rb1S2nkSXW7lpWTAGv8rsQaAcWyc=,iv:W6G7+0YVUqVV/B9ImnCyTtyycntthmtSnw0s5WmS6o8=,tag:eizQT64lFjzC0X+0+CWOpQ==,type:str]
  version: 3.13.3
