---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gatus-conf
data:
  base.yaml: |
    security:
      oidc:
        issuer-url: https://auth.kalexlab.xyz/application/o/monitoring-gatus/
        redirect-url: https://status.kalexlab.xyz/authorization-code/callback
        client-id: monitoring-gatus
        client-secret: "${OIDC_CLIENT_SECRET}"
        scopes: [openid, profile, email]

    storage:
      type: postgres
      path: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable"

    alerting:
      telegram:
        token: "${TELEGRAM_TOKEN}"
        id: "${KALEX_TELEGRAM_ID}"

        default-alert:
          send-on-resolved: true
          failure-threshold: 3
          success-threshold: 3

    ui:
      default-sort-by: group

    connectivity:
      checker:
        target: 1.1.1.1:53
        interval: 1m

    announcements: []
