---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - network-policies.yaml
  - rbac.yaml
  - conf.yaml
  - secrets.sops.yaml
  - cluster.yaml
  - cluster-backup.yaml
  - github.com/AlessandroZanatta/gatus-sidecar/config/crd?ref=v0.6.0
  - endpoint-templates.yaml
  - gatus.yaml
  - ingress.yaml
  - service-monitor.yaml
  - alerting.yaml
