---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  namespace: gatus
  name: gatus-secrets
spec:
  secretTemplates:
    - name: gatus-secrets
      stringData:
        TELEGRAM_TOKEN: ENC[AES256_GCM,data:wdRL4GaZ2GPJIi/O/pHdePSmO0IOaQIAe7WRTt/Tc/oQc0m7ASGOdVkPX6Ojag==,iv:TTjTHNRcJSW188/fN1wV40HfHo6wH1Nnrtur176i/8o=,tag:V+86z2n1v/m1cRWRcEAdSA==,type:str]
        KALEX_TELEGRAM_ID: ENC[AES256_GCM,data:nFHLe7qLifMCyA==,iv:ZjPb1r31IOLkNq4lA05kpUx/0zgSB+wEWgy9mnQvNFE=,tag:NyqbUTDQse9Xonm6/0Pz8w==,type:str]
        LAETITIA_TELEGRAM_ID: ENC[AES256_GCM,data:4kWmqqRY5DhVGQ==,iv:RVWj81S2H4e0cMoV5nhFIrJ0Pc4ocskpDoh61jTPkHs=,tag:FFk+zp4/N9p6yAGhxRJ+BA==,type:str]
        OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:erOm2qag3HPMyfrX7Zb8CO76BuHornte0VFZyHydbxyVlnUblOXGikCDd1fDWtZb/z7ED1WCDLQLCUsTiOTA++VqDrc2GvwJ1xxTutG2GG6mOVgPEdOG7FqMRm94jpYYTmSa2bKHvKjfmuvqo6Pz3FosUK7wm8Zk8Tbxnx7Sf7o=,iv:D1tNw+eY9hksunSaO81Oz+eOtwN8pn/IsRJTa+jjLsU=,tag:pY9XZZU6b8wokaKksyes9Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaaytkWTZlZ254NDJJWXJq
        eFZnS0hENjFka0RKaUhNeG5hUFBHRkJzUFFjCmRQL2lHRldvcFNLZjlHL0VRWVpD
        d2IybXJSZ2RvcDh2UG1EaFZ4U0tUU0kKLS0tIGJWaGl1aWxidVJJSzFkMTZDRCtO
        anVveVRTZkFhU2k1YjRLalVEY0E2MkUKTfFpsmVVDAUl+zBZmB2yL0N5XjRG42Te
        k4aB4UuQ1Q/WsQViqaRJbE8bVmU55201HAw9ioOgdThvSqrhOQkqtA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ff26etr9n8nsp2ve2lkh7w4dqd9g9m9u3y8aw77ureu639mrfatqmuqnhv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-30T11:51:40Z"
  mac: ENC[AES256_GCM,data:RxyNcftIo3FnfCZP2VRKqvkc7mjh8FgyUYdsZWUXbEhDLCD94CwL9/1PsN8EeTkDzy/0ziywye1Qq7Id7md/coaOHg3sc3PqEzKWCZffWgohiU4ICj9ATEeuPO6/8lJw/GayJqs7J1AllNtIf8ZYklVnMSA3zqGmSAwxWIScVG0=,iv:bCiTnYlcOYdCfACPZ1Dpx6Ntz7N1Q7ZZUuwAeRMdvyk=,tag:J6T5UWm/mutpkAtA6Q7NKw==,type:str]
  version: 3.13.3
