---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  namespace: gatus
  name: gatus-secrets
spec:
  secretTemplates:
    - name: gatus-secrets
      stringData:
        TELEGRAM_TOKEN: ENC[AES256_GCM,data:6CK+Mm2/egJkQ73rBwCVvkZSRDs7M4a0rnJJzwYWLK/P7wgK0hpEJfaVnpS3wA==,iv:elAD2PO9hO4QUjUHzQky+VnPfINdqQap5qE+/Omt9Ok=,tag:BT7NmdrG8jnvR/XV6KeWZA==,type:str]
        KALEX_TELEGRAM_ID: ENC[AES256_GCM,data:m4B01OrzQSShgg==,iv:/OhLAFLVAVkhsc+T6VszpyzKJggzcx8TFPsynKuIMno=,tag:npRNGuxQXFenF2GQNNVl5w==,type:str]
        LAETITIA_TELEGRAM_ID: ENC[AES256_GCM,data:GR0LD7q/zhNsAg==,iv:gopgOnniEStftbY3A/s17/09Md25pkGv35XA3xHii2M=,tag:KmPFWeZDk9FMtS7jv0dGag==,type:str]
        OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:wpG/EW5LEn+FfUlD8nLfV8KwOZSwE/XFY+5mAvOoLN9R3ZS1Psa+1LhkxZAvT8muDEiqK9YuF8vMP/kamuzYsvN/5VEPRPsX,iv:Vh3Hnt417BRUC1dqW5Ku0ZTNQunVRAZMSIsMdeK3F3k=,tag:uTaBsKX3jZAqdSD/rlHA5g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0T3dzaWZiR0dxOTA2TjM5
        RmY4b0tYNU5mcit4TFV3NEJsTGV2K0RLLzFvCmNDVDdBd0NpSkRQSHgzZjRvU3Ux
        cHpmVThnVnF4T1pSaWdZZVU0ck14blkKLS0tIFdvUEptZTBmdExLZDJ1d2dIMHF4
        OEtpWnpCNW1wcmtVeTQwMndvTWlPREEKGXVDupB9XNJBl3FFHSHtCem85zPUyarF
        18s2M5JwWTadoppRi41YlW/3Rj+SdQJeVVAdk/cpPA5vPTnaNM03XQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ff26etr9n8nsp2ve2lkh7w4dqd9g9m9u3y8aw77ureu639mrfatqmuqnhv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-06T12:07:17Z"
  mac: ENC[AES256_GCM,data:94i1xqWGK6IlhfNbqwcLt1tteXQlTfPN9Eh7t8/vaYNGlsuk1XDWRHM43LYZ5LDv+/TD+uW0x9CHTl9n+BSkmTkjNNZH2kgFjbdTPR9omMSDoVL9lMlXJZluKkMBP2vtx87C2+3NZHnykOoRwePlSQw0jK03DKb+O9bd+wosuf4=,iv:bM+mauDK3COMOXYb39WoHcp+UzA7PvAmdYKfeEYiZwM=,tag:1yuLm+zUU+nXsTBsqsjdsg==,type:str]
  version: 3.13.3
