---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  namespace: wiki
  name: wiki-secrets
spec:
  secretTemplates:
    - name: outline-secrets
      stringData:
        SECRET_KEY: ENC[AES256_GCM,data:S0ppwIuGRjlSCf8MdStZ0VrCBOowy7FlZPf+PCOQ47JvHvDudDmlDUrPt0ydE51nQBKfNVrfGlw1V/hPVjsNKw==,iv:5B2SxO3IkVtLF39v+ZKv26daZGiMQETdRKXpI+4WmJ0=,tag:IdFLOo5zx8O+GbjwQBADmw==,type:str]
        UTILS_SECRET: ENC[AES256_GCM,data:BMVWbmYCZLZEAUUpKBAa4KN1B5jWdk15FclP2EUa17YNvbcwikqqcTZnCKgW/NTXF43gbhCCBZ1TF/A7cz04Sw==,iv:2s4zbG5ni7oV5eWZ/Dg25LCnGY+0w2L8pD6e9Etfh40=,tag:zIWmN2my/qORl5SB74etWw==,type:str]
        OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:uP52xXeHxQhkLqMYuydjSOFq0WFNwHrKuzMKx+F6cxxCONdUVodzAv+D5h8X3cUhPEzTvVLJuPgggruWP0niBESMAZVZ4MPR,iv:Fhadw4MuMIY1Q1IFDFvq2yqYKAUOcJEc2p2wi+gl89U=,tag:4ybXHmmmZRL2wfQx7Bgu/g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ZXhRMEhtUDJ5c05jeXl2
        U2V6UHZ3NE1KWllVSmh5NmwwNk4yN2pOZnpRCnpWbFVOSGNRV1hOWkFBanphQjU5
        UGsxSHJLTFNLclR3YmJJSzd4ZnZkRDAKLS0tIDFsNHhHNkxtT2ZPdm1SSUI4a1hE
        bDU0M09kK1JENlRJUjRoYzNnbHVQazAKqFLUOLqGq3+EagHPRlaqZJVTE46ldbJE
        DA+JppNjav79aHGSJ+AruXVkF05zaBvF/KKuGmoEudFZvPlaGTh7Kg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ff26etr9n8nsp2ve2lkh7w4dqd9g9m9u3y8aw77ureu639mrfatqmuqnhv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-06T12:02:00Z"
  mac: ENC[AES256_GCM,data:NiT65/C7UIYguyNAK4ERWzr3AZdxEWRDZk7RtsHDlbkn0cWhYrGBWmHTf5A31nnSTdZVolQrKF5p3rOl87iQolfic4J7U8s8OC0PUHqE+utlJy2Z868X2Ssnl+A4w8x5HOH8MxgL5sAX6/AOQx5rI77NehlCDLHRA2zTnRG6ikY=,iv:Ra7ZMnwIkkP7Jgs6cMQcuIEAQeWg8FLfgyrp929vDyM=,tag:wrGvGqJVFCUCeFqTMUox1g==,type:str]
  version: 3.13.3
