---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  namespace: wiki
  name: wiki-secrets
spec:
  secretTemplates:
    - name: outline-secrets
      stringData:
        SECRET_KEY: ENC[AES256_GCM,data:8qj4Io4oG27R9JUbdvaRKj++lwEWS5rh9z3P0DOCYi2xEbSjOTY6fe2vjvYLOZg/8rZNIhqDmaJ8WpMdwy9xlA==,iv:4hucdAd/rIit4+g62t6KezEke03VS6nKaVzufABxRRM=,tag:ZhFzldI7lRdTkBm4tCEc8A==,type:str]
        UTILS_SECRET: ENC[AES256_GCM,data:d++ulk1q58BEAlku4dp9UI+O4VAOlOk8NJt5PQUFsXGMkCDE2V0a+6wlu5O9FjhQz/aAcfHfCNJp3iemc2A4dw==,iv:Y3tjWYgfp/4Ki5dcvpXsOf+a3HPbX8/safQzEJm0SAs=,tag:QgLN6ZnzK4fa0f3fWHbAlQ==,type:str]
        OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:tNMjZQvCY7s+Edp38G9lX4sMAPG6c7RuBECd61Y1rigj2kw2EtqgFkNK5YfUgvezVZamiTLLU5su/ffmrdppOAykgSWkod2Z,iv:ChLATmbhdSNq9pvBkZObVT5ucbHLC/i2QKT6iPwidbg=,tag:HEepKiu0b02GLjl8YMHocw==,type:str]
    - name: s3-secrets
      stringData:
        REGION: ENC[AES256_GCM,data:8zC4GZsGSg==,iv:/0mrKAz8QL9TAET7nymwcY94biAbCegKR0mHzC8/5gs=,tag:iHl4swwuUb1SdalBKfIDvA==,type:str]
        ACCESS_KEY: ENC[AES256_GCM,data:jjwIiBQ+8V/NkhVEDN0gaakdEqD6KLIaiK0=,iv:f5BGTd/ThJDWJlZZJXCrO68PUDsmbX23Znb02IvR/yU=,tag:ro8YXvwuQ2E1IxR6Yw96Uw==,type:str]
        SECRET_KEY: ENC[AES256_GCM,data:/7BUnrvn9YQ+s8EwRkRWeTZ+Y2XuXnBSkEaFPMNnhtKkQ8zPtZaQXutQiX3lFscenqc86yTVlVvAZnIZdsORGQ==,iv:9B24mHm9FEiYfw0PWrRMpegIBGQydqbyV/ENWwYZi2s=,tag:4grxRReQKXD4GllSh8sAqQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJbVd5Si9vL1FBZWVaMUZo
        bzM4cWt1WWEwRmtsZ0thQTNQYjRodVZrKzFZCkdGR3YyOFdJaytGM0VaY0VsbzUy
        KzQ2K1ZPR3pjYjY2ZitIVU5NSjZnOHcKLS0tIEtGOXhXSlhtaU53ZnkvLzdKRFA1
        dTBaa2U0ekVqMGZnVDByRE1VQzBEd3cK/NI5vLsUnhkpQvkOYncjFMcdYnoPo1Xx
        TDEGt1hBpxTlFEVMNtvfPF5QefNlTlCwznsESqeOZi9bim1s3GgK6w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ff26etr9n8nsp2ve2lkh7w4dqd9g9m9u3y8aw77ureu639mrfatqmuqnhv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-06T16:11:14Z"
  mac: ENC[AES256_GCM,data:vkPr9tZV7MR5SlxGHa18juShH4djqxYuB8qxUXaP8RPCNCH1JRqNE/bTPGZNvk/Sgnh7iBBU2NE2kItBjmj4hOq1bOdxY4ngjC8gxhEl3ML6qMAZD8QLYiecRXAZHlqAFdS0NzZbYhGfdhEgCTiToKG+AZYPXf0GxlLrtULrwgQ=,iv:zhYYL7WwpZB3mfz6jF0jpfMvisTU00PNC2bnPReb/aM=,tag:Wtxm/W5gLj1DjDXB/3yZ9A==,type:str]
  version: 3.13.1
