---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  namespace: wiki
  name: wiki-secrets
spec:
  secretTemplates:
    - name: outline-secrets
      stringData:
        SECRET_KEY: ENC[AES256_GCM,data:kaAshBCfNXiLMujAKrKDpHXCaElspbELIJvI2xAC2RANRv60W0HpBvi+jQI/rKPoefPzQUi1RZ1Zdh9QjB9wjw==,iv:9p9H76niGlh/D358Kw9nUeHssg4jey808lSA6Adq7Lg=,tag:KCyR5CPz3A62mplcnBe2nQ==,type:str]
        UTILS_SECRET: ENC[AES256_GCM,data:pknxFcCUHswRSSyapREkCgv5NYkKq4qOpGXleDGAOzLFfI8qNIrgthFNOopRD4vnx1dxcO5b8OWRa/mSWdwLxw==,iv:eHvlpxrOUQw3XlIt8TTMaqbPIS75mwxJgDclx9/8L/s=,tag:4LD1D5cSR4P2vOKAjPDcNg==,type:str]
        OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:LSwLszXE/E7o8CK2sauMXC+0pmmdcb7aOVhH9NdFKg/URVYVHu4cnYzxTQNGHdK6KfarXRKBbI5iWhJXnKCNwP54qj3BKJ1Idfc/rLS7cqx8wtySxVNTDrgcHA/8ii4XLp/58RxcO5BMkdHFCnPUalVr5Errlr23BKXoG2fAsZM=,iv:i200fs7kms3b5iBAlLoOnDmLT97mNh9OLgs/jzHvpy8=,tag:bUl/NtjCHMTFg0UWp/xGzQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkOTVhRDVJNit1cWRhdVow
        RTRObWIrVE9wczc5anZRU3ZramdWTGM0aHlRCk1FUzB2VHpoY3lSenhmL0Ixejhv
        elloOHluRFB2WVUwand1WE1ibkJwSm8KLS0tIDdRT01Jb3NPUHNUNFgwc1A2SWFE
        N2JpVmVNV1g4MDVZNHltVTdZM1dRUFkKfoR897eUZPeghfnQ9eqpUcDdc41umfd9
        ULOsQy4jKgIgnkNJgLmnHvDRS2MO58G2zP9zcoQXmjPz9TwuzCMzWg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ff26etr9n8nsp2ve2lkh7w4dqd9g9m9u3y8aw77ureu639mrfatqmuqnhv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-30T11:30:51Z"
  mac: ENC[AES256_GCM,data:BMoZYdjw06L1D0cX1A/LKStdhuHBVPNe9mYdpdAV/tG4lBuga652JJqBx2pr4C5sEkWymmu5i8GSVTR7P7I3AllQOyPijvZTFho5grNkuOhAL1q0jvfhOH+LDWJE8BeDFmbUbX43kEX+5npR8mdch+NWz/zP+zhYXZ05+ULgBPY=,iv:ZihVDtXUlhsGn08cxh7BhquafQ/k3MWt1wUnHBBH2To=,tag:IuIT34IsIxve8tO2ZX0FTA==,type:str]
  version: 3.13.3
