---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  namespace: books
  name: books-secrets
spec:
  secretTemplates:
    - name: shelfmark-secrets
      stringData:
        EMAIL_SMTP_USERNAME: ENC[AES256_GCM,data:bpqy6s4Hl3tkNONrYy9eHVEklIdHRYiR92crjQ3c5WI=,iv:60+/rqn+3yrrlPkiibM4QabGXdKLwhgDt2xGZcFnZ+E=,tag:EBSqsGjiyDzHH0b04LK2Ww==,type:str]
        EMAIL_SMTP_PASSWORD: ENC[AES256_GCM,data:rMrvgZRhkGpwdp1ea+qTMSdFAQ==,iv:cHr5Q47fmEcF7TfOKHta2oA23G3tgXq7vnJWBCa5XyY=,tag:ZbRJSt0GzEp8nB9hN+oWlA==,type:str]
        HARDCOVER_API_KEY: ENC[AES256_GCM,data:0b/2ip2BcJhiXzrovmQqSLL7XWI3p2Bgi82t7untyuJ76DcFFUc2nCr8h+rZZ1htRXD7z+ZYP3nFIgHqWPU8/AUJPf+2iSKx+C0NGEZxJgZBlSA2CWcQw+Mi8TybC6548eBRe+OLpJQJqFoofpq2lpeATxobAQeRUJQ491ocWv2Fv12PEJDQC5aEkZ08yfXcjlZ3NzUilUAQeebQRobGZS5LvSBI65mRacOFBTWIQeWVqTxCuW5QQBX8FGY5bspMzzFeU7DtygkW6BwzUp6DIeX85TMAeKi+vfW+PZ/Pygyr57LnLvR/7oL4AxPTHZTVNGR+GKcNki4t3VnpvX2UohRwu3L+4i1MPEphqdnOlU0nzaYA3wugUHRbfAtmacIjI1OCns+XeX1yZ38BZScnAb3nmAyqoI5D1NOobgd2k23DFD1WJgufqbHJdKP7wvcBb0RRpOA7DT/E/VsqCNXFTktQUa8MDL5mc53ST4MJ0PoaTO1C0xKxelaul3EkazaUflwzkoQjceW6iCINha58g3a8Kjg5TbTDIhV4yRLGYLNXCT6pNHsS06slKr8veq1Ts7UnGFD7XX+7oQdVmJ+8oPwpeF5grLRFrify36xdQxVRgOhe/Da1ZmVecW9IdTLxPlh30Kj6lueL4rvXI1NMaIfOb75GzX1Gros4Lo1MWuh50wBMrsRqonDx6om6NVCUWA5jQrs=,iv:fh6qjbzXvuTQw0ZWqHRNlDe1MQ3gusnAqvLvlmIx13Y=,tag:pbxnTcY47feHS7XmGH2LgA==,type:str]
        OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:UzYWllC0YE3iMffJWRzzKSs4Ysdwhz4VVwxLVSoEVkN2tXXVm83UrURbN/XW22YeFyTIFBblU3KmesLQYtEf5sXLDW1oE2Ms,iv:91kT2VPduNBfQGsJLAftxMTD14FCle0zf4qDn6/k21w=,tag:C42jGIazBUd3OcKQ9hYJWA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpb2crVlhnYkNoZ0tPRWNI
        N2U2RllUQ0hMdUJMRlFydy9mWTg1ZWY4UENZCjJvSjJoV0dXUTlsalNsemJGOWs5
        UUpXTVdUQlRrVGExNHNOd2NUWGRrdXMKLS0tIHdPR0UwTExiZ2VObURiNEg1N2t1
        RWR0Zkt1Ynp0U0o0OUNYWVlwNTNqU3cK6GIygixMqj9TQ8GQjuivQhJhYs6K2cJB
        YwiCak6ugqm+foWJetclU3D/FaS8KnyDvQw0P2Y8HE2yW6Hp1wUeIw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ff26etr9n8nsp2ve2lkh7w4dqd9g9m9u3y8aw77ureu639mrfatqmuqnhv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-17T06:21:24Z"
  mac: ENC[AES256_GCM,data:uGIcRFCgXy9Nxb4mj8P3aaAeLwY0Zr/l/PJnAKrHE94z30iOLEvISKkp7pC/MNhRB7NyJ35XJkpWt09bFZ+eFSH40MwEo21PEJx8q6BBqGO4oOOshFPnATBVlPHd2ocDKNfVg1CXfb1NohR0KJ4+VvyqdBqmD9wIK8Ly34G/r60=,iv:S9vzUEvK65xy4prEfZ7u3HXwBrBckKujVL0RK6301Gg=,tag:Am/g+Xipril9WB1KK5ONRQ==,type:str]
  version: 3.13.1
