---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  namespace: books
  name: books-secrets
spec:
  secretTemplates:
    - name: shelfmark-secrets
      stringData:
        EMAIL_RECIPIENT: ENC[AES256_GCM,data:+PLZoJ+ih9Hb1+TmJOp8SP7YRooeF7tp8nPJc4wY,iv:ROOVSBq2RBnT+PkRbIuOZKUZyqMJqi7EAe6MmkimEqw=,tag:FYoc4RGkdfkbTDaejwhxIg==,type:str]
        EMAIL_SMTP_USERNAME: ENC[AES256_GCM,data:zp8tcMmEXAN+31WW5RKA0DGIoOX07PSbXZmgI5oI0ag=,iv:n2wWnQn7ax75Y6H8GsOloUZVUXZvfrvneJvCzjBXULQ=,tag:2BFmU+wCvZrRRdQHNXZ7Ng==,type:str]
        EMAIL_SMTP_PASSWORD: ENC[AES256_GCM,data:YYFS3CgLb9885w8oyp/7nPUtOQ==,iv:lyPR8ewt8rSqnR1xMZ6+F1M8Vim7AIRDd4SpBimi4XE=,tag:Ny7s0932GypbxI84EQCD1Q==,type:str]
        HARDCOVER_API_KEY: ENC[AES256_GCM,data:54V6ZTIaUrdDo5D3vJ04uQ3EFE35UCq6GMc1jdoIc5ZFM/n/AbKITWC9G56FoQSjp4Z7PbbBguMeQOqCi48LBVotAun+bxnqx6RYmQDbHDmqu3RO/cP3OO9SG6t+QicmRah3a5ztPJEQJa6vZqWDkJAxpeLhbsMADvZgjsqI4N7dEuez8yCVX74U0qvHmMdjJYgq7HBRU8BzZcOROrJJIuIXw3fGWKxuuipayb6wDqnzDzbirhyDdDiMO2rRHKl9Tk4DAMlV9wjrlSn9Rs35NimDUwwNGNMwLXSImv8yV5wuMJ+7aUAjNsQvXomQtyG9SLkVGFyoh54WAOQz1sKK8+nqPPTkKVJWeIem7yGGP01bQDFeMEtibvKTj9jcI/BuHf+CyMoeZy8sR4e1bVyocqdBt7GcernmQbci727dSWJ4nNElBdFjekq1OUN2bvY1rXeqFZ/tnYp7mJcIRB6xPfHpVz7XUlpcPzxslKmDQRkGZ+h9BI1ZrYhyFUhuA1bbvYTkl4T6T5nKfTOKKM9/YKrrx2t74C4eR2RohL9jLiuzgHj2yBAMsptbfxWbdgERQCZcnoZ61w039s1bcIAI662+6Qsdu+asM3sGkgBUTr4B9dCBnUUWyi56qv0b/TaRhBX66GNcBYF/3CZeYCu2TqTO7eufa7lU0wPpt34qpukthsVRGeZ0dmOK7WH400RxEZJ6irk=,iv:60y8IiO4MHd6UrAfDuYz6zyZMk2eIRgKYcCECbRDKtA=,tag:XzuRKl79qIjyP8Bnmihgew==,type:str]
        OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:v/vEgUPYc7mXrOcnKdfX50QTb3ohPzYRUG43dcSXgRXqlt4fTh0fmiS8NRoj1h6610bPTzF99sMK0Epi3jAmO2ajFGdrLFvy,iv:xW3/URrlmddMFCa9U2/pcbeb5crMlw0zb3XV6b+1WQQ=,tag:G+LqJjeum6jvzlN7DUWwew==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvMURrbGExaE1FeGNndjBP
        WTg0Wjdpb3Y5bDZRallMWit4WTM2WWtmQVVrCmxSN2xPS3JZYmt1UytSZVUwWE4y
        VjNwNEJUa3JyZWFFMGxzVmF4NWg2RkEKLS0tIGFDTUhGa283b0oxb21iUUNabjEw
        dFB0NWRKT1hWZi9yeWZtSDc5WUJJQUkKE+jMXx3tiVTOgO9slfr3ntNk2taaTbSs
        iDTe52ENVXFpylc9SWF5aMVzVHgwcSlVvlejK/0YDFVQx4ekIFuQrw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ff26etr9n8nsp2ve2lkh7w4dqd9g9m9u3y8aw77ureu639mrfatqmuqnhv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-20T13:11:01Z"
  mac: ENC[AES256_GCM,data:2Non7vWQ5nOzuhjbkvmoa1f6Uzlvg9G7zNd8TlZbi3smudKDa7959JzvUUIdJ7Bv5S3ao6FTxyKHkpc8Jl19tKNao+efIAg9f2tJr7kgdq399tKI2YLtDaPW1QI+RDatd8Mekczyu7VI0JwHHnDHZ5pjr4jxulGazHuduA1CApg=,iv:J8ucorzcnzXhnLZ8cs9duAYw8Dj8rgihJH2/u3xV3Jg=,tag:ySq0LGUCKkb/sl4DE99Vfw==,type:str]
  version: 3.13.0
