---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/AlessandroZanatta/homelab-v2.git
      targetRevision: master
      path: kubernetes/monitoring/metrics-server
  destination:
    name: in-cluster
    namespace: metrics-server
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
