---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  namespace: nextcloud
  name: nextcloud-secrets
spec:
  secretTemplates:
    - name: nextcloud-secrets
      stringData:
        NEXTCLOUD_ADMIN_USER: ENC[AES256_GCM,data:tC5vJ+M=,iv:HJ5ZOrTxdGJMgtFMpPZT+2lTuzflY5FfNu4pICAjhGE=,tag:2ZE7QyMtIEDA8tHjJzKbmA==,type:str]
        NEXTCLOUD_ADMIN_PASSWORD: ENC[AES256_GCM,data:rJxVoDg0CyAcAJdZ5s2IUQ1ABjAXbLXzWcFPtIP2rkZnwVRL4b0JucFKiShESEAsOjJqKUs15KG326Qs2i6aHA==,iv:Uewpvaw4ycpLnIE2cfrxso7zBEi+Yn6r3p96hx3BGjQ=,tag:o1ctWFk2QuxeXciluuYBpQ==,type:str]
        SECRET: ENC[AES256_GCM,data:xZV/4f6PFh+z3WFUiJVXoSuNBfBpUeOjOe7zwfzhccM3hlbscsnRCIMzG4SZKYc0,iv:bnBfcbqGeDI2zYY9PitmLtqm4lH0sErAj72dop+1UH4=,tag:KYKfDlf524InqcZkPOjmaA==,type:str]
        OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:NWdcWjgdD1uW/Gr0zJ9SL4Ezfaup73v+EfEDNnAiPOJ9+M+2eG/Xb/ndq+B6ycvZ7AqFT3nAedOHu5LD8628aB+W6hvMnpJ0,iv:RsmkNMmAfMMoLowcmd8dSa69qfOxhcMP+/xNbwFTDbI=,tag:qHZNyXW0ep5HA6EbCGEgRg==,type:str]
    - name: collabora-online-secrets
      stringData:
        username: ENC[AES256_GCM,data:z7xNjJ8=,iv:M7JEjnuXcwX0U53G1l2WalM0KqQUDVxlHZhS0Z1Y80w=,tag:GYlFfMw/dP2WDT93wiy8hw==,type:str]
        password: ENC[AES256_GCM,data:0K3qcubUPU9AGYcr2nihk5uyQqYUfIaMYeP8w73NNRXrc/JJ7jL7oVhoVntOvw6ssxxc8XvovPsGydHfofVoLA==,iv:LAFYJBl8wDUz9Wq21nZycmCRbnxIbVRuU22I+AngvRw=,tag:j9FdljJVA+nqk9zP/oKXYw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpWnd5MHl4eS8rMUdqVTl2
        N3R2NW1VLzhxdFlKRnRrU2duY3p0UGVoUEIwCmhhcG9kY2VIMkRmWjYzYTFISy9G
        Um12SHRRdjlPN0VNYUQrS0YxNXJiQ00KLS0tIGVvVGF1YUlQcnZkZlhKaWVOUFBx
        cmxNVmtQS2FvUldHQXZwK2Vkek5OTXcK2BFB0s0/LhHVleiRIRAuuThOL8mMLhO3
        ty1WT7ipsohEqQ6VqlkF9c4TckVn4V5birbQckZbprJmjYfZAI4CPg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ff26etr9n8nsp2ve2lkh7w4dqd9g9m9u3y8aw77ureu639mrfatqmuqnhv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-06T10:23:24Z"
  mac: ENC[AES256_GCM,data:ONyhKrwKrKIN25u9MNgfEl3OR8B8bQFNUuOeu6blHvQlsbutAgo6WVHKAIWe/Cp1VFGuxYAvgiYYCmOe336Mo5YwyRpZtjxiuIZeSIgGpQtADKefDYKEmrLRpW6x2SySHHpQgy3Vitw/o8M1KzsslXxuMfOMZ4xCqDFHUMtQrQU=,iv:oFgYqN/cSQnRiOebiQ/lCs7sRnnS0QkKNajIAuO9mcQ=,tag:4oxlH16etUJEjQblPqQemw==,type:str]
  version: 3.13.3
