---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  namespace: nextcloud
  name: nextcloud-secrets
spec:
  secretTemplates:
    - name: nextcloud-secrets
      stringData:
        NEXTCLOUD_ADMIN_USER: ENC[AES256_GCM,data:+M1tokw=,iv:dRFEztmeBxrJWpuMWYj1Itkba462cWqmNPc9QTltDqg=,tag:oSDgrRhHsiQiGC93LocivQ==,type:str]
        NEXTCLOUD_ADMIN_PASSWORD: ENC[AES256_GCM,data:M4U3vZp/X4kEW0nHMSdGtczu2IH7rku4FG3h+YanZIo3GhWHSNM35HYn+uosm+qx7hqkcD9cp7IxAUjsLQbGbw==,iv:x7tjFMCyrHMDmLY6bSSFET12kpADfJXrxG2clhu6lb8=,tag:TLm4bY2B+/mBY/EX/eoqXw==,type:str]
        SECRET: ENC[AES256_GCM,data:djPC0j0F2NX94wscZoeAW+K8OTaQqiEKR6vfn/WGpG4kqqH95vAnYuay/tFyK/PO,iv:q7qNGCB7eFF9KKKI9v3lX7yf8PToT0h6rMA6Le7f8w8=,tag:50W+WBNDme7nbT5Sv77NfA==,type:str]
        OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:wzYgLY8gLHfWBLsyX1PF5aFoarUe3x3Xzs9PDX10kCPpORsJOZrrwSztkqtVuOa0Q+Si+TzxI1CcBETCADreUamnmKeC5CKR,iv:28DObJDuCHvzz7HcVaAiA4K0EDj3hLQruz+w3nXt2dc=,tag:Qnv2Aj/Hfg2zqeXEZFRpGA==,type:str]
    - name: collabora-online-secrets
      stringData:
        username: ENC[AES256_GCM,data:kp4GfaE=,iv:nrJ61VdNpi1O7264tWAMlqz+8nuGgyVTzAs9jn/r8bc=,tag:HLVVUjZKc0oeBi8cdXCSBQ==,type:str]
        password: ENC[AES256_GCM,data:MsyU/77WGxjLrLpXfFwFlAzMxtph+X4pZtW2wa/EVhlTp8tem6HcY/KgRMyRA2L+BiA+icR7t9nOAwhFcWoCGw==,iv:303yVrskKmCXeUY8m8PGxlV/cL8r9csHcQJLlRwkPC0=,tag:k2+7FYbhuZZdBVGY3hFtIg==,type:str]
    - name: s3-secrets
      stringData:
        REGION: ENC[AES256_GCM,data:/e17lBuONg==,iv:TMJbcWiiSlOIHzWJue9ey9x2ZoKIJaVzzJB5cnZTVa8=,tag:ZrIlghAE2JfBirfo1Khp0g==,type:str]
        ACCESS_KEY: ENC[AES256_GCM,data:PtlI1Imk6MNJUup9JDf2M0/N6HXxY5C9GIQ=,iv:+/DoHTWQhn77Yu4pUI2FG7eidrsKjxZUJWvpMOauJ8A=,tag:BW+6VI7zrx6jgtfQ0TBanA==,type:str]
        SECRET_KEY: ENC[AES256_GCM,data:zTDOfh7SESXObVbeCpw8HtLsFmxCycpBEtmpcv7ztoVBmBmpmbATntSHzwcRTEGbnfQTyDp/ooXVJ6jtPkhBwA==,iv:RL+3sziujqE1Es87XdM4HBIsRYA8svNPcfYOrfODBVk=,tag:LDRDm7oNXZL0nIQ+FNWKRA==,type:str]
sops:
  age:
    - recipient: age1ff26etr9n8nsp2ve2lkh7w4dqd9g9m9u3y8aw77ureu639mrfatqmuqnhv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwU3BhOTRTQ1A1UGg0UXpB
        cTVMT0Z4T2xMQlZVUGVtR2NlelFoUlB2TjBNCjc2S3NvcjJCSGhESEoyNW1CWGJ0
        K0hHUFFUTmRTaFFPTnJSUFlMTDN0NVEKLS0tIG40L3FmdHptbUl0UEhqaVdnTVFr
        WTE4eUtqdzFlYXVONG9iRy8xMm9QV1UK5T2QaOPb1ujZgDkAR2CaEmQa90OhofJr
        FRhpIx9s+5jjIzS8QFmBuvOzGQgvlh86sWkUsrK8aSwpk6nb5i0P2w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-10T13:01:17Z"
  mac: ENC[AES256_GCM,data:v3I5onRcBv0VaGYNYBLq0yaxS/cn9sy/BdvtDDaq7sd/YweR29htKpDhGOVS+z5V7a/NqlzWTcx5Fpt0gW2JsawV5HzP5onwFyX6PHVDZsd7na5o817tvifr4x6w7kiwXCGhUALVT50b47kxDZcsxap/qk37wnsDqVXIdaQjaQ0=,iv:NWs9R/YqMpPmMcBBHq2OjAEDtVA29TotDaWc3ZrzeaE=,tag:pGX8UVlYA/m7w0f/+sblJw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
