---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  namespace: nextcloud
  name: nextcloud-secrets
spec:
  secretTemplates:
    - name: nextcloud-secrets
      stringData:
        NEXTCLOUD_ADMIN_USER: ENC[AES256_GCM,data:XL7hwlA=,iv:hnjrRd4iTUlRjfPhBa0ZaKdgyjwKXgc3RMiI2FZf5f8=,tag:HIPTfRsmL1zL3yrNdBMm6A==,type:str]
        NEXTCLOUD_ADMIN_PASSWORD: ENC[AES256_GCM,data:/yA7zlU6cflG2XYsDMhFh+MW8UXad/hLvhdv3zqB5u/jJPmBLL6kDkjhmwHJsu0AA4U06JEhnPPd5iL91FVR0Q==,iv:REPT2CIGRJZF+/aVmrZNlB4RC7B9pJqi0RYiRyB5INA=,tag:+p84peFdcL1Qtuaf9CKVNQ==,type:str]
        SECRET: ENC[AES256_GCM,data:sUcZaK4lDnZJFpvFgqkqxaPy35zxCvU0uWTy29OP+dzbdNWj0lgV31BbdQXWVHkt,iv:hu8NxB1FrXDW6pwnWNKnKhSc+sNAex4wKGDwHr+TCN4=,tag:Ud7GJ8dR/NKJXSiD948KAQ==,type:str]
        OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:NcpLWR4yCViaiy1+StzyLat1N7JcTd5WLIQNJqay7KMeSEWeyVB2Li4OigQTUAfj9H0ETOEo4NTm1ANfD2YbuNds90U/hWAJPRbPT0oJqBz143gnt1wOs8l/8zRXdg1Mh3Q6tHRx6PmNk+cS0RCRjup8QDxixU84AHnu+BPYXJU=,iv:O6fv5YBHb4Ocl29CH1fjbmyp+kq1+EEzlypRNkK3yH8=,tag:9TymZpcuvoNf+8fz2a2KYQ==,type:str]
    - name: collabora-online-secrets
      stringData:
        username: ENC[AES256_GCM,data:Mp8UrTQ=,iv:2QKtuIcdZ2Kmy+SJ9U21KcymsZ9Pr8D0ZnbAeNkeBU0=,tag:giUJCjl2lhovSuMsMC7BHQ==,type:str]
        password: ENC[AES256_GCM,data:fe9eszPuRu11DxeTCecoGCtBu703KOrnMP0jHyj/9xwHpqTVpH7cu3dgCcLcQ7mH3/85/OHnMCPppAGF0x0Uxg==,iv:5PhRbB403f64cIvpYD1n/tcR0xUBsZGpeEsy2xfCgqg=,tag:YYTfUXPahmWZIupG13ndXw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0dHM5TUhCUWFqRVJVWFZD
        dktJdElMQlFQNGswQW5ZcEU3azBocTU3SzJZCmlMcmR4RXE3ZFBPSm8vbVZZUEJp
        eVpZU3hwVG5XbHphNmN4UDErUTNnV1UKLS0tIElFbU1HSklTZnBsTnJneVJjRk5u
        Um84N2NIYWpUZ01meURLeHRTYm9NSTQKEdUtOS2tUaXZ/+eIQHWaycQPzClT8Xjq
        vuQ8f3g5GQ7JJLIIppqyyKboe9MmqPg5JC8c6jakrGhYy5pyl6tjCQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ff26etr9n8nsp2ve2lkh7w4dqd9g9m9u3y8aw77ureu639mrfatqmuqnhv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-30T09:59:53Z"
  mac: ENC[AES256_GCM,data:emQWsgDZeo/Wac3/sVumh2NO19yh2vMPlWLrJQdPsKNVYX+VMGEU4ufbIkduZV/eHElnH02uhOFqkMSmAPYETYJhYycNt9omxsIuvsxe6hhJ24K3eDbguGbgurxRyiXyKrk3NlkzdY8PgpyBhfHUkY7QfuMCzh0zCJO8/9IVksM=,iv:92hVOqA+7QODKM4Sq6YI+nN32nCrmw6Ae6DjQAM5N90=,tag:+h5lclOXWJJ6qK38rualTA==,type:str]
  version: 3.13.3
