---
initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.14.1
    imagePullPolicy: Always
    volumeMounts:
      - mountPath: /target
        name: plugins

metrics:
  enabled: true

  serviceMonitor:
    enabled: true

configuration:
  volumeSnapshotLocation:
    - name: default
      provider: aws

  features: EnableCSI

  backupStorageLocation:
    - name: default
      provider: aws
      bucket: velero
      config:
        region: default
        s3ForcePathStyle: true
        s3Url: "https://backups.kalexlab.xyz"
        publicUrl: "https://backups.kalexlab.xyz"

configMaps:
  velero-volume-policy:
    data:
      policy.yaml: |
        version: v1
        volumePolicies:
          - conditions:
              pvcLabels:
                cnpg.io/pvcRole: PG_DATA
            action:
              type: skip
          - conditions:
              pvcLabels:
                cnpg.io/pvcRole: PG_WAL
            action:
              type: skip

schedules:
  daily:
    schedule: "0 4 * * *"
    useOwnerReferencesInBackup: true
    template:
      csiSnapshotTimeout: 2h0m0s
      ttl: 336h0m0s
      storageLocation: default
      excludedNamespaces:
        - kube-system
        - velero
        - backups
      resourcePolicy:
        kind: configmap
        name: velero-volume-policy

credentials:
  existingSecret: velero-cloud
