---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: zigbee2mqtt-secrets
  namespace: home-assistant
spec:
  secretTemplates:
    - name: zigbee2mqtt-secrets
      stringData:
        secrets.yaml: ENC[AES256_GCM,data:6A7PbVtpB28UMCA9xIqj1JUTN6mm1ZL0oEhVlNrhvov3vw2w1fA4SGLb7m2ZM9zSxPQjqvYCWrP2QjMDJhU5s/7UbIwVFVgIKktivWZ+iFxmZvc+x0jgw81tkwZYdK3iwRikDXUygzm3RmyGPbY1EyKxWaZp2bn+kD9BxKox9cIreyFaauEpIWOWat6Yh3zPooA9IOzLxmBkqv6TZaABOPN2iLQ=,iv:ce66ZemcWRY80gsfgw/FQ32YQe/FOuDy13ryJxsddIw=,tag:EfIn16TfAwOK9cF80BDNIQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1b1l1QU51KzA5WHVWaW9N
        b2tPZmQ0V054TDFSTXR6Q0RJK0FIZTFVcFhVCnJLV0dwTDBwWThES0gwS2hDYm1R
        V3VVL0FtNVZuNUpvZ0VnbHp4Q2lNRHcKLS0tIGVFcmJlc2RyWGcrZGlwbkN4YzY3
        dEMyVSs1aW5vNjFBbzBhcjBvRkM5ak0KpvGGfVF/DSAwgkGBDmupkq/TCJp4ubtR
        ugbvlCe/GvZV3v6JsKcLKIH6iS+59Ttugc+czaoh+WnfU5Zpe4cXIQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ff26etr9n8nsp2ve2lkh7w4dqd9g9m9u3y8aw77ureu639mrfatqmuqnhv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-29T14:13:06Z"
  mac: ENC[AES256_GCM,data:/y+JVuVtSGLeTjAATWCZUDbA9tOkwipUpiMWkTHchgp4HVzlQz7OqSdVB6LyNjneq5CyxDSWr80Q8Jxg+rJ8eRLNz70xe9J6JfXB0evS4i+96PJCT+vlbAKTTpulZYzQ5gpUudwSQMjoo4egndapOHDCR0cVlFmFgJH7QZ08QbY=,iv:J2c/Dkd4a3ufdDYkO+PsDV2aBxfWpJdxFP2byOY1ZDk=,tag:8Vk4bsDivcKcNiqlmOJAVA==,type:str]
  version: 3.13.1
