---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: plants-secrets
  namespace: plants
spec:
  secretTemplates:
    - name: db-secrets
      stringData:
        MARIADB_USER: ENC[AES256_GCM,data:dqezd4AaSA==,iv:OW6Xh7RyqtvJCOmlGTJNl6HNPDRqOMZYJjWZugS9axc=,tag:5QZZk3dEFArz1Qca+dm7tA==,type:str]
        MARIADB_PASSWORD: ENC[AES256_GCM,data:rxoBbe3yvYvONYn3twjTcCdClv2tmlNiSIASeChgYk8RwAGV7yBwunh5quIm/IWI6YBXAkXnBQE4vnTjeyhPcw==,iv:KtPeQMniAz9VRO+G6f4bE64wINDbkqSiBd/KlS7M2uQ=,tag:Gq22usrmG9gba8/4P3T+xw==,type:str]
    - name: hortusfox-secrets
      stringData:
        APP_ADMIN_EMAIL: ENC[AES256_GCM,data:pPj4t4Vl2UlE3V8UMY3j0Pjh7fMVEzYlF51U3Y8aR+o=,iv:RHrNDa1NpIQatMxD+wKv/IfKHQyI4JWlj5Omwbvp5JE=,tag:aEWe1Fwnt5pikV/sl6U5ew==,type:str]
        APP_ADMIN_PASSWORD: ENC[AES256_GCM,data:sP/j8zkaoNn031i+wGehfYzlbfzxf8i3eTmisZYj/aKFQ+EdyfMPJviGS2eI8UWq5xsVbrZhtQypr6/9gnBNtQ==,iv:q/gA9wI745unML9KU/7XX3/tTIH3FZ2jHjpmCOoWgkw=,tag:GRQQZ3iRB2InG3oD0+qOtw==,type:str]
sops:
  age:
    - recipient: age1ff26etr9n8nsp2ve2lkh7w4dqd9g9m9u3y8aw77ureu639mrfatqmuqnhv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTU2h5SnZxVHY0VTJFNjAv
        SWc3S25qUkdpMkxZcmZnTHdlQk5IZytXSEFnCmJGdm5DUWRyRW5FaVlaZHdNazdG
        bkdWR2tMZUhOTFgxeXFDZUpJUTFYVWMKLS0tIDVRd0JBMjhWZmR6Ry91ZVlqanNP
        WGwvclpRSGlaT0czcWJRbTJyL3k4NVkK8wHwN8wPLSlV+g61obPjLj8TH0HjrYmZ
        v8OV4nBbGjEXzZRftuDksueozs/hD0Xa2ZPjl8mQpdb5BIXQIRRCZw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-22T15:02:30Z"
  mac: ENC[AES256_GCM,data:QOMfKePjkrRDdNDCOqqYCKs0+x9NGq/CpJxywHlR3L2pMyvGY5OI7cL05NKJL7iDGBlCo9q4i5VWsiWpcYj9rfF4VNPH5Z2gkg71GA1SACXfJ4wFjOYFKuOgfxiQvclIzRkYjyHbc1/TjrJ7ZWh6jdWmUTYw4xMDHwH2DJQF6jc=,iv:zz5LCxgh6Xvk51cVesusPogtDQoYIpSUam23Wn5axgM=,tag:iIQtypsg4ng3+8eeh8ADQg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
