---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: plants-secrets
  namespace: plants
spec:
  secretTemplates:
    - name: hortusfox-secrets
      stringData:
        APP_ADMIN_EMAIL: ENC[AES256_GCM,data:7tSisk3vzHRym/NrnWCYfrCub7WzXyYI+98NKiY38BM=,iv:WTKyKDwXZhud9+MVQfQ2/2BqmyXzrlj/BYUuYpYFjqM=,tag:cX7zJ0R6Ck68f5FEQBMiRA==,type:str]
        APP_ADMIN_PASSWORD: ENC[AES256_GCM,data:hgCEDHrVLqU9RDnBe6ZJcwJ8Rx4uok3DH9+gBY5tvKhkDCpH22TjTo+2tNTf+l0AjqvcwaHF8O8FOJUVtQUzfw==,iv:JmD/8QYwAKzJDl700FZpAQ4CEV775KstfRwDMWWUKd8=,tag:7r3H3NmG8eTPIuRZ763Ytw==,type:str]
    - name: mariadb-root
      stringData:
        password: ENC[AES256_GCM,data:4z0P3hkwljodPZCRPiQrd68rafZX+/doJSDai+xpFw2prM8WQgdg9OvMXiPWk6zroipjadMg7Hv8fFCUQ3JZwg==,iv:lB0TGtGc0NxdlM0HPez12yoKgrP729hJCMmOWX83zAg=,tag:q+EXCUGBK4W/53AxQPQGrw==,type:str]
    - name: mariadb-app
      stringData:
        password: ENC[AES256_GCM,data:L24bu41qQ+D3NEIvcBphnaZNODmOoKEm1ycrDJsFtBw1ehNYZgv71mSn1uTYTTdAkkYRzPn8OhFnPuGBEE5BWQ==,iv:2cH+cOiEHSneh3CkZPzTg3UZ9XNNXAL9ipr8BaTJu6g=,tag:BiGkejbNMDvG73iODetMhQ==,type:str]
    - name: mariadb-metrics
      stringData:
        password: ENC[AES256_GCM,data:ZZosfFIfffiRhhH1jDS1BBsDjXvkksaRwUToaGGc2qRsNuINHvYJxMtaDO7q2P3c8YZueegU+rJ2IX7Huar9CQ==,iv:ycSmPHe/ggTClEfPnbzKXx1qE1z2TteDakdohQ3sTKY=,tag:uKlUaoEa2JnWRBpBX5N+gg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJa0IzaWRobG04SVI0em5X
        MEwwZlEvRHNkQjhiZFQ0YS9KU1FONjhtSkR3CkdCNDR5TTkzbFh6SGpXZWJvcUtH
        WFdobnpSYjF0bHVkWGFMeUY5eUhQV3cKLS0tIDlRbUJ4TE5jVHYwSVcybURtUEln
        RG5QREEzYyt2MEIvaytMajFEMlhrOEEKoAhs1y7rTpw506F2dr/TA7fxoYaMJ8G+
        3Lj5Jinx3fXd1L8iRU64JcTBCI0SbeSLhKBbNU/xEsZLRtUzO8rhnA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ff26etr9n8nsp2ve2lkh7w4dqd9g9m9u3y8aw77ureu639mrfatqmuqnhv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-26T06:49:25Z"
  mac: ENC[AES256_GCM,data:3X6z28gbE0/LnsssROj70OqJieOxG35sNQAOcSTZKQRJCIUPqiZZyOAGV7/cA0qcmbE7XS8BUCSnBrGz6JzZqOaOQR8GyEYl0m8JS0tHRi0lRY3EsKZtOmZcExgLzC1kegJOf0Q+bZ85TWiygRVksbMrLfvvw0G6fb0q0vdN52k=,iv:YCujU+RJr7qqsSCCJ5xeryWr3Gt0YKqOVycx8/7kgts=,tag:0Lo2m9nWAdgeiGAEWj3U4Q==,type:str]
  version: 3.13.3
