---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: plants-secrets
  namespace: plants
spec:
  secretTemplates:
    - name: hortusfox-secrets
      stringData:
        APP_ADMIN_EMAIL: ENC[AES256_GCM,data:BPT9QX18LVxrKGiqL6KYLd97tNmAiI5gncCVLmm/Ckg=,iv:bEX1ciUMMFsqq6MuzYuwfQtf5kUMkq2vHQ9Fx+V8AKA=,tag:6E9eH4Um4+Hhp+MuJLFJjg==,type:str]
        APP_ADMIN_PASSWORD: ENC[AES256_GCM,data:WFJHzeuwEyY+tPreDN2U8LVkfaEySoQXFOVYlekYX1szI1uNIjvk+gQkEfe6R3s5GwwRDtTDYZbHfF5I+68hkg==,iv:rsgABL3hIsXJ6vO41tlHwsfSdNBmLYAj28KqTj2w02s=,tag:orOHauwWNKnC+sCiOp9mfw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkb21WTzVLSnArdERjUEN3
        aGtHVkFZb2RscWpHVS85MFlSUzY2M0NMeXlNCkx5a3NuNVRtTTVoM3dhTzhkdU9P
        Uk9UbHNTRkg0eUw2ZExrT3plQ1FKSlUKLS0tIDZkMVh6MVF6S1NBekhiN0tPUzBK
        cGRvRGF6cW83MzNwQ0JhTy92bGVkc2MKtngoYEAtIk5MyVk4HCSK5yQMmdzIt8Jq
        tuzcWrQVKLczSeB7nKqJlasPkeQ5x+XhmSC3g+ZZ2GXvHunOSd1zGA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ff26etr9n8nsp2ve2lkh7w4dqd9g9m9u3y8aw77ureu639mrfatqmuqnhv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-25T19:08:45Z"
  mac: ENC[AES256_GCM,data:eOjwCqKcGotqXkHGPGRqb6ys2wz7UOE+tIr4WEqqxHZBJoLoIvHIK1qU2T2333/Rn9QAF3Y7JBg0BvGs28luJ94UrH0oMHuIxitK8i8LhLFFl2xPWtlPnlhG1w2w74uNRizgbrCzs71SNx8g8Aj6BxVA10KDGFlpnR1wL/HmxvU=,iv:/7qi80Ukjg2LHsH+Ag14taaLAh6nYUu/USboxA5yApQ=,tag:ICfDPHlKWF1+tSkHc+kEeg==,type:str]
  version: 3.13.3
