---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  namespace: books
  name: books-secrets
spec:
  secretTemplates:
    - name: shelfmark-secrets
      stringData:
        EMAIL_SMTP_USERNAME: ENC[AES256_GCM,data:m8JnMDRI6IrKK27feZzjoFk0OGL+gphgxMlNKLMQLv0=,iv:vJw54LhpqzEk0ss/wqKlhI8HtPul0ig+ZBXBZrXU/Q4=,tag:JMob4B9vG8eApCQnXr8hmA==,type:str]
        EMAIL_SMTP_PASSWORD: ENC[AES256_GCM,data:fmD3lWgXprNC+QfjHvkGbbmPhg==,iv:2qCk0vbWKOsWxBDZMNKyiulPRCKievM8rcEJluj29Q0=,tag:NSE9HzQQt3PhJdZL3HLfZA==,type:str]
        HARDCOVER_API_KEY: ENC[AES256_GCM,data:dtELBuLN84/Dw98eUCiJKh+KhxQx3MapkugXE5gw0+tBAow6240n/b/6WurqQFgdbLqP/e2++e0csjhYi3ZhwzJ7hY+/PmDTUyjDKb16L5ET8nUPloMIKdvjEXGx6kc18b/TZlo6+clMbpWELTboNqH7XnfbJpi5afFV94JdBfdnHzTiMIzsTJlt+ix8XFWRpHKFAGjxYizj1K8zm8ckQ56svc6pEqpPHT5YYxrYUonRRTVEOXdbY4ncK7J6cigQW1hZla5c/rt69W5iKlQNj7P4yVQag/VINYCDvY0sY39Uh0GnSMrUct5fb2S1QqBqi0XzSwHWfDDkpLzjz76YWNT/jbs45OIGYt0oIbd3jRzk18Mn8tJBfIKu6m9mZAF1c+Xg7iNv16V9I4w8CLwEK6vnsvPWbLWFPqyOweOJkhiE5LT6e9amEyHefBEdVhkfuHGeV3xPCJkPim1zKtZhD1y6Xg9aUB6U7LBCJXLwicex0UOMCbUgbE4g9BQuhigMOZtW0cRS5oh3D7Kla+SKZDLyMkZtA/eUXgaJlf8aNYMv8+nEIHzAM5sIuCdAsCNnhii9oOhLnt4rcOzQNOyAlUC5VdPHOKxFNlxHoDrZv7R/J6AI8YNlC6YWLK75XsLOA4LZW/Rbu2ABppVmG8mtP28YgwB7h8KAKcSXLERD9XLNT/gUnKPPOxCZwajtO3vbcHzFSaE=,iv:nsR3Tq2W/zRfS07tTerTHEj8u8lgO8JZQCNElvEO4/Q=,tag:9wT4+OLKnR34Wf2ZNkVB4Q==,type:str]
        OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:UJI+4EbiM11S1eyIi+Q5smxYnd2meH/ZHvCnxiZ/awFXmqFIqea3jkYyZxeNhtArV++Yvbb9wnuH8/qnjreUSOb0ojc4y96N3VZKxb5mRgzPUAS1el2uaqxikhdEXUAZdj1LDn8t7Il4aSk8O1vWydeaNUEMVx42D/UtbRgVP+8=,iv:HfbzJ3kwXiXf8gRQhs/T5DI0ZNUeMBunCZKWjR7JdiE=,tag:hA4GMf6qE7Cd9hrWlb+YJQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1VTE3eHRGNWlkdzlkMTRD
        b0FOazE2UnhaZGd4NThuMlIycHZwRUxwazB3CmlKU1JDYndVSmRENzhqMmFEVFY4
        ejRTLzdsV2Q4Q29FblRrQmVxSjI4S2MKLS0tIGxzejhnRytZcTJYd2IyVG5lUXJs
        NDJKMWFNNDdVQnE3dUhRVDRCMTlLbjQK+pBWz57DsAVcbGIOD7SgDVvf7ON1FhsZ
        YQ0d9YeMgqtLodahiAHFWhoDi2S8Wg2fy54DhWQaSj4AemvTV5gsKA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ff26etr9n8nsp2ve2lkh7w4dqd9g9m9u3y8aw77ureu639mrfatqmuqnhv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-29T13:46:20Z"
  mac: ENC[AES256_GCM,data:4HoTB42VHCOktqO7aCPIWzU8Cco5cIzIThmtNBammJ6hJwvbnpUzs2ASStPwIiwrZfa2syqy6brotdANch2CyCFGK7XWj4CeNSIifQ/kop/2lxpVQcydxtdFvAjit5NTfLVdgxz37mEZgLnolafwMQmQnNVzF+ryCpPZQbBSzV8=,iv:mSEOVfsHefnP3oZpaZSh1ap7KybC2CojaK9gOdjhd24=,tag:erX/22161EVmyf5LVNa9tA==,type:str]
  version: 3.13.3
