---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sso
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/AlessandroZanatta/homelab-v2.git
      targetRevision: master
      path: kubernetes/management/sso
  destination:
    name: in-cluster
    namespace: sso
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
    syncOptions:
      - CreateNamespace=true
