---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ak-outpost-proxy
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: authentik-outpost-proxy
      goauthentik.io/outpost-name: proxy
