---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  secretTemplates:
    - name: secret-key
      stringData:
        key: ENC[AES256_GCM,data:XMAoJ9L9S+US34BYwqwlkesUThVJ4M+ORksa/OSHWcm77TH982sqmlw/VE28NriZ14kGQ1PnnwZoVfKYBBNadll/xMniZAsjpEMVkssa6c8n8tpG2Suzhg==,iv:CoARqLiXB688GdlFc9IEdhOm7gmwdeyQxQYvETxkdkA=,tag:kwxP73JJUO/eqPoKugL/Vw==,type:str]
    - name: bootstrap
      stringData:
        AUTHENTIK_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:4LgXXrVwjpSWX3wznT77PpO7,iv:OmBa9HSlCNgQx6o0ndgpUMeoQsKRH2kawrKvlRz8tfw=,tag:k6jZLZOs8DVnyT2AKGlkYw==,type:str]
        AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:0htUV36lBPs7pV9fRqJJY+c+grcyfqVZaLmTgrhDfFl7dGUnEpIUWwpyU6anIJlg1d7OZD83bYRyRha+kBbzIQ==,iv:AW1UL1jA7krxZjNX7nDu6BEi7pOI8gE9Ddv5kYWY7jM=,tag:bdu6aCjuR50xhB1BmCYVBQ==,type:str]
        AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:xXsrU2VE7VeOaDCk+RYJqhNwVrcLK0suT5VccbQhvr/hvto0/DKWg3lgNoTqR8Xfiy1ZBI52hOJYzRxgkOd+Rg==,iv:4nlvjn7Z+vORQhbuUI+AQogbyYxcnLE+T6iSzBSO7iw=,tag:dPkXsfHpP+fe+/n6+mM9mA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUWmUvb2lDcXV2anM4bFZS
        V3JnN2NhUzFKeVlYbThBMjBlcGd6bXAvVEJnCnNpOURZWU41N0xQYUtBTVFMUDRK
        RU1VaDV3eGdQNmlZS3c0RmNCQkszMlkKLS0tIEJOd3lwZk85aHhlTTZYa0NEZUNs
        OVpOMW9BamtLVVE3MXk0TW9KN3NLN2sKaiMbf2FcMG4pZu9nvZctmTIQ1OJTLlAy
        /i8zADr0L0cN9DpaL76ctCyZ6dFadHBpFyQBJWCgo2zsNG+kEF+z8g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ff26etr9n8nsp2ve2lkh7w4dqd9g9m9u3y8aw77ureu639mrfatqmuqnhv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-10T07:25:39Z"
  mac: ENC[AES256_GCM,data:GzfPdvvZZie1f05EE3TzKqzJi7F9EUqEO74h5cj5cf35AErywI0ZT0MRBZREPq/oov9sKRcv1cKeUvMHzSNufTsCznmv3+mIoSKtB4BnMVsH6sr5HbVxaBXYkyLCQFNpbj0N7odXjH60Ga1aR+N2gRFMcfCsGHdSbbI+SEe8RvM=,iv:+VdR2x3ZICKh1IzZufds6J+ovSoxdBt1+m1ynbtrg2g=,tag:Xtnk4vGPqQXn5DWSU3/mKA==,type:str]
  version: 3.13.3
