---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  secretTemplates:
    - name: secret-key
      stringData:
        key: ENC[AES256_GCM,data:rJ80Owo/ULz/3DP9RzSVl1Y/jce4F0r8Sga6QqxScm4y/s8BFx5OzRPK9LvC5MafCLFQ7sZKUwn01Dubs9kO6S9GROVXhfC2XnhTgPV1e/iIa8bZOeBzPQ==,iv:ALBrTl+6DM/YV/r9WZJNhtJ+cexzSIq+S2LeUZIwYWE=,tag:RP89Qp3kPlwGwHo4BjnE7g==,type:str]
    - name: bootstrap
      stringData:
        AUTHENTIK_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:R1sTaxwZURavvFUOO0hVU4Sc,iv:R6Xv4eZAv+GITiWF56L4AsQ9XZrRDH5WKuv6M+iumUc=,tag:fvoW1+e+Ldl68hUWfIisoQ==,type:str]
        AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:F2vmnpv7oCuamju6f01COCxfDBLaQvLLKwtffs3ePMrAgkfQ/AS4voByz64380QyRYpVXKZQsDsKoc/rnTUMVA==,iv:vpz9D0tOHTHcDWUqRdN6ei4ONqRRyGjS9BGeJy4Mp/4=,tag:r+KSgJRFKcgCChTT+1QZow==,type:str]
        AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:J74z0/KE2sEA8QR96H5Q9lsmqcEm5Vgx0FNMQG+D/S4DeLX3yuV37QE8x+/lzAqDD/jn/uufXIauCPwTJpTqxg==,iv:UyV7jVu9hseewPkLTJqvMBHaGuI3pMGKhi3hRJKPn3Q=,tag:4yi9aJrzupL2PsBMoAxdDA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoOFN2VkVadVNnVEVkZ0xX
        S3RXbHRrRTB6WFB5M3pxbDl3RTEwQVlnL0Q4CnZFWEdTa3gvN0RrYTZGTi8xakMz
        eCsrbkQyUnlCcGFBZmNrK2RuM3Zwd2sKLS0tIHhhRGRGeE5QVHRGM01rWE14d1dr
        YXRFK1VXUlIrZGtsMGkrMlRFc0t4d0kKJOyorA4xmx5XltTAmNpDR0dH4/BYDU5L
        jxW1RxqZI/pDfSFVXdcLZeVkfB+Ze3KLY5BWHZowwMgUOuzT9wRrYA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ff26etr9n8nsp2ve2lkh7w4dqd9g9m9u3y8aw77ureu639mrfatqmuqnhv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-28T07:19:59Z"
  mac: ENC[AES256_GCM,data:L/K4nbl6h7LKxD/R92VccGu3jK6L7MqrMKnsfDqZAphhFEhnDGaAd8qb2C6AwNMuPW9t1Y+WuPuSN+8Y9osDPjxjbprmyL0pcnXS8cFItYsc2J5HEQ6HHQYy3nD5McE1cEI5t1VfxlM2H3jXIsFNOV/2oowyAOcUNJxjUVgOoCU=,iv:Frluo9am8BQ1o9q6QpIZtEhjr7V6MJ37WrIDoxocSSY=,tag:TYV7Rr4HqMxHcK7yxzbFaA==,type:str]
  version: 3.13.3
