---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: home-assistant-secrets
  namespace: home-assistant
spec:
  secretTemplates:
    - name: zigbee2mqtt-secrets
      stringData:
        secrets.yaml: ENC[AES256_GCM,data:f4rDLcQvr3xDrnB84gZonBTLRUd0hmDQ0y6gKqEG2KZ1SMgMXhxEnN6D2LGQRJ4N3PMgE5Fk9Ug+MfiJSSN+VQNO163wu9ZunS6QFvetjj/7mTGhP2ZWYWU78y8bO7wdF6DTWkqMQ4tQjTgS8fXH9KFMpRM2+0/t7mOZ6+wqeUSS1kpCJlLymYGnCE+SOgfNGv9w70xgSx0L07HdqkFJeQqaKCk=,iv:hDjokTj6GJPhIDJt0+FLOytI5f+iF4e+xtYNkeYLMGY=,tag:v1iYJnkJDmAXNTzeIHNVmA==,type:str]
    - name: home-assistant-secrets
      stringData:
        secrets.yaml: ENC[AES256_GCM,data:rl8JwgZq9gxFCDE+tGG3Emt4/ghP1OUXcI7AETU568zkIDEJYMd2U1wuyig8xcXKKgmKb2/jA0BmOrnEm4W4EU9Y+GFYdrprkY7+kivnqoS3iUEzgbiZ4QUmheyFQbRvQLqalpAaVmDryGFSjBq/HHOKV9M+47dUiBIuHElHUfxf6S95x2dQTgQ+QowQW16cW0Iteaw/RmVBuVw=,iv:wof2CWCWQKP71QbCdGDYQ8YDnV6b6yqWFpeDeQRH3KU=,tag:jkrPaeAGLl7Q7vb3l9V/SQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbmZoNDhlVTIrNEs5aCtZ
        TXYzQklyOC9NQUhLTnpJWElWRENvWndyeFdVCkpPOTVmSDlzVVUwL0ZYcTZxMm5G
        NU5OTTZLdEV0WVU2NWVNNmVxVnhmQncKLS0tIG9mUGZJZm5rZHNJQUNmSGV2QUxO
        aVI3Qzd1VzVsdzBENWZiZllwdlNLV00K+51O4hVHsC8NWEoilwPl1ybR1tL3RA4N
        ztoLC2mj9kFw0YTnE7tjFWWyHlQubbAfO2qzMFj4QFLgex+/l2v55A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ff26etr9n8nsp2ve2lkh7w4dqd9g9m9u3y8aw77ureu639mrfatqmuqnhv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-29T14:00:36Z"
  mac: ENC[AES256_GCM,data:EU8DLbJ0BGKEcDp/rCkySvKsUi6txJeMNRG4HcOCXNSqlUpPtj8WB+3bhqXDt+oskzAlHRRiN9NFsnKOYFPELl6Les/SV30GJmSry+zmmlyQRoZzP6VPYYcwqnZwZkGx2Dqm8xfOo4GLmaQExWI2XSN1urJmimGac421MY3O99c=,iv:gfBpYFbtjI0FmPdZkpCWStByVpAKp25Rm6gURntFqzU=,tag:CbuWVdsZ/604zDRyB12cAw==,type:str]
  version: 3.13.3
