---
apiVersion: v1
kind: ConfigMap
metadata:
  name: anime-conf
  namespace: anime-v2
data:
  config.yaml: |
    base_path: /api
    server:
      cors_origin:
        - https://anime-v2.kalexlab.xyz
        - app://- # electron
      media_path: /anime
      log_level: debug
    redis:
      host: queue
      port: 6379
    flaresolverr:
      url: http://flaresolverr.flaresolverr.svc.cluster.local:8191
      timeout_seconds: 300
    auth:
      base_url: https://anime-v2.kalexlab.xyz/api/auth
      trusted_origins:
        - https://anime-v2.kalexlab.xyz
        - xyz.kalexlab.anime://
      email_and_password:
        enabled: false
      device_authorization:
        enabled: true
        verification_uri: xyz.kalexlab.anime:///device
      oidc:
        enabled: true
        client_id: Wz_GlwcKKwH1UHM9aQAk7otNLb8R_D36zHvWQSA~BNQZ0K.rIqTnPa2tnFC0dnL8FbADBX-f
        discovery_url: https://auth.kalexlab.xyz/.well-known/openid-configuration
