---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: anime-v2
  name: default-deny-all
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: anime-v2
  name: allow-egress-cluster-dns
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: coredns
      ports:
        - protocol: UDP
          port: 53
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: anime-v2
  name: web
spec:
  podSelector:
    matchLabels:
      kalexlab.xyz/app: anime-v2
      kalexlab.xyz/component: web
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: traefik
          podSelector:
            matchLabels:
              app.kubernetes.io/name: traefik
      ports:
        - protocol: TCP
          port: 80

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: anime-v2
  name: api
spec:
  podSelector:
    matchLabels:
      kalexlab.xyz/app: anime-v2
      kalexlab.xyz/component: api
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: traefik
          podSelector:
            matchLabels:
              app.kubernetes.io/name: traefik
      ports:
        - protocol: TCP
          port: 3000
  egress:
    - to:
        - podSelector:
            matchLabels:
              kalexlab.xyz/app: anime-v2
              kalexlab.xyz/component: queue
      ports:
        - protocol: TCP
          port: 6379
    - to:
        - podSelector:
            matchLabels:
              kalexlab.xyz/app: anime-v2
              kalexlab.xyz/component: cluster
      ports:
        - protocol: TCP
          port: 5432

    # Allow OIDC with Authelia
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: traefik
          podSelector:
            matchLabels:
              app.kubernetes.io/name: traefik
      ports:
        - protocol: TCP
          port: 8443

    # Provider search
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: flaresolverr
        - podSelector:
            matchLabels:
              kalexlab.xyz/app: flaresolverr
              kalexlab.xyz/component: flaresolverr
      ports:
        - protocol: TCP
          port: 8191

    # Metadata search
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: anime-v2
  name: worker
spec:
  podSelector:
    matchLabels:
      kalexlab.xyz/app: anime-v2
      kalexlab.xyz/component: worker
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              kalexlab.xyz/app: anime-v2
              kalexlab.xyz/component: queue
      ports:
        - protocol: TCP
          port: 6379
    - to:
        - podSelector:
            matchLabels:
              kalexlab.xyz/app: anime-v2
              kalexlab.xyz/component: cluster
      ports:
        - protocol: TCP
          port: 5432

    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: flaresolverr
        - podSelector:
            matchLabels:
              kalexlab.xyz/app: flaresolverr
              kalexlab.xyz/component: flaresolverr
      ports:
        - protocol: TCP
          port: 8191

    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: anime-v2
  name: queue
spec:
  podSelector:
    matchLabels:
      kalexlab.xyz/app: anime-v2
      kalexlab.xyz/component: queue
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              kalexlab.xyz/app: anime-v2
              kalexlab.xyz/component: api
      ports:
        - protocol: TCP
          port: 6379
    - from:
        - podSelector:
            matchLabels:
              kalexlab.xyz/app: anime-v2
              kalexlab.xyz/component: worker
      ports:
        - protocol: TCP
          port: 6379
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: anime-v2
  name: cluster
spec:
  podSelector:
    matchLabels:
      kalexlab.xyz/app: anime-v2
      kalexlab.xyz/component: cluster
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              kalexlab.xyz/app: anime-v2
              kalexlab.xyz/component: api
      ports:
        - protocol: TCP
          port: 5432
    - from:
        - podSelector:
            matchLabels:
              kalexlab.xyz/app: anime-v2
              kalexlab.xyz/component: worker
      ports:
        - protocol: TCP
          port: 5432
