---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: anime-v2
  name: anime-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 150Gi
