---
grafana:
  adminPassword: ENC[AES256_GCM,data:ixWZL0f+oHONA8blCDWdFnrgnvXUO05wpwCaZgmCreUAFLQNOxL0cPplrjD0bLDu8sW3tcFY9ZFUFBJRbPCekQ==,iv:/2QCdEdXklleFtIUEcARJ7IG4AdOmTLQdUW6DMyB4/Q=,tag:9Sm/SQAw8UG27xlJGE2B3Q==,type:str]
alertmanager:
  config:
    receivers:
      - name: ENC[AES256_GCM,data:hDzxGTm7KwE=,iv:4TtBmws88PV+72mrrusdgDWaBdAqFI4k4CmWDbXPbDU=,tag:d/dcWe/oQaTF1yxDq1lVBA==,type:str]
        telegram_configs:
          - bot_token: ENC[AES256_GCM,data:DpbGfG7QuEiQb6cu1LHBWP8yLEg+kQIsQsUBBnfRLJjX2bINA01ntvFCCLF2NA==,iv:gXMJRu90c5waA1s/w2ytZmwDmHbeyqSUk+O5z6Mk+lQ=,tag:210/qe+7s0yzvhmlECmSrg==,type:str]
            api_url: ENC[AES256_GCM,data:yetNdXm+/Z9Ey76m2QeCofbIqQ3jpPJ8,iv:utaKWd406xdDAaapjk1ip0YhXEhSc9NB1AP78imTfB0=,tag:gKFkurllTDLQTvC72sCs4Q==,type:str]
            chat_id: ENC[AES256_GCM,data:9cL/Z7ywLD9uZg==,iv:dgGm+Z9CfPwrqX7gm4cy3GgwnW2wPqSooGv7CaLgdWA=,tag:Ib0cmy4q3dnVfVniWX2DGA==,type:int]
            parse_mode: ENC[AES256_GCM,data:9yjf+w==,iv:yUXHoj5wWlmYDZkMiIMNi2EajNkzTuZL5dfUo1T+yaU=,tag:TMn9iAPHRinoLHYkK3QPGA==,type:str]
            message: ENC[AES256_GCM,data:73zCwuu/echAju9MXu1S1C1koJ+47M1987/Bx6rT9urG7Uk=,iv:zwymbunZKPzpmxHZShCTWkkmOw1b8RtFOc7cEsiPkj0=,tag:EqXxvG9MEdK4IO653AGWYQ==,type:str]
      - name: ENC[AES256_GCM,data:QS6FGA==,iv:XHpZviRPQFAD9i6wVsrskr7tx2Uoxfg+bodlbGLVl0s=,tag:zcaafMncLF5iFCA7aQ+DGA==,type:str]
secrets:
  client_secret: ENC[AES256_GCM,data:vrZUYreDAbRTdqeFGKwt3QHFvSquVbzp2o5wZa6AEw/vgSlDRDwKPCf9Hbs45+1ieocUxGFK90L2xpg4IVtpUbh+l1eZ3ros,iv:Se/AWmHDdTlaIObcGErp1RSoBJbnbfsKXEdjnX/nJtE=,tag:nOgmrQmnRoCsw1W8IQcMXw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkbFRhR1JvYVlOMk03U3BO
        OVJTcHAzdHN1M3JXZTJmSXZTN1Vxd3NXRGpzCld3bXFJSTQ2NU9XUHBCcVJGdUYr
        SU5WYzhYZmt1YlZheW11amczTGZOdDAKLS0tIDZLdzcwRTBpUnczTitNZGo1TlRB
        OUhMYUh3b05hRmZxUEdiYy84bnIyMk0Kl9PcftKYrU1fgUOFY8WW7D+Gi1kO9Rqc
        OrNqy6Xd2e8wehHd1/nTax031GU4Z1cXdvXqFtd5VshwhBM/HSCJyg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ff26etr9n8nsp2ve2lkh7w4dqd9g9m9u3y8aw77ureu639mrfatqmuqnhv
  lastmodified: "2026-05-21T08:11:37Z"
  mac: ENC[AES256_GCM,data:HAzSQktYsWfduKv8LFk1nurh38aFZZDNmt5h9fAiQFLD9f6+OoAfOgsMBNsNZ/UV25d1aSoSchnNuv4BDUq1eLCSJA6aOY/RcX8GgJ5Et1cRMsg+niqcUFC3DTD6jJbY62xRdglHBzxI+qgBf9pGleW7yERl67IQz0yN65eY8V0=,iv:2DYp77GyuHZOKSFx1G2UOdyym4IFwZnaTTjJhEaepQU=,tag:tsbUF8YUqG3A11Pm3ltnXA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
