---
grafana:
  adminPassword: ENC[AES256_GCM,data:KjqonSykz2YZRjxzzxx3Q9mVfXlVcLZAyCUwIOumfRkZQSnErsikkkdsQna3D9P/Y0lqiCjQ7x+PozKVHyKuSg==,iv:EeP6bpRKPlVQN9ZRDCKvGQRxUzjOhC0QCU66w9p5Lys=,tag:8QvL7CowU4rTnDr9beSRkw==,type:str]
alertmanager:
  config:
    receivers:
      - name: ENC[AES256_GCM,data:1ywMlyEY5d4=,iv:U2T/HMEJ2deDp5ZZXrigQvz1ObWWzHnUwhxEjbSfx9c=,tag:4kTV/uWBX3JZWWa6tFRrZQ==,type:str]
        telegram_configs:
          - bot_token: ENC[AES256_GCM,data:8qH2YCt+HwMB7Mjw649QH6vHK8Eo71VL4v9MKJYkT90cFj6YjG/8qMnZuqPHcQ==,iv:0QpQDZQkHbeBWu4ObRvb+YvfzDG/QuQfIZhR82BMzFk=,tag:lfh1f3f4GX/FXvnQ8ZqyyQ==,type:str]
            api_url: ENC[AES256_GCM,data:HVSgpmIStvN4LCWUdLUeb/sdgAG4U4nP,iv:XuAqnUyLU6yBg2aXo9GmS+mF3AcM7fFu16Mza/LwQHw=,tag:peKO9v+vFJqc3Xwo6FUqdA==,type:str]
            chat_id: ENC[AES256_GCM,data:W/dYbE7O5bTpCQ==,iv:SpZ3iAvIS8A3fAJyzSFydKxzASOCKo+uiVaPCFiUa5I=,tag:Vm6M6pIipOkZJQA3ZI/BtA==,type:int]
            parse_mode: ""
            message: ENC[AES256_GCM,data:O+Vq55gefBo5onwj/LyvGh8PiZ0Zq4MNFSeC2oWlbfCyS1g=,iv:KKff0VMWbDZpjJTpnSdmlCLbFANFfkDxWfdBtVWBSFc=,tag:g2t/zckf7PRCuJTMfcX0vg==,type:str]
      - name: ENC[AES256_GCM,data:zKmX6g==,iv:6y4bnGqfC2dKrQH2imDJT6kvN4Sf8iZ70VyseZP67v8=,tag:r7NPzk8wuRKLf5oG98cBpw==,type:str]
secrets:
  client_secret: ENC[AES256_GCM,data:QYkEGIIAaXNWhCmL9fG5T2Z1cF+b59HCRWWUMqKRWzn+ieOrUC4DsEK0MhGRwMcLccYci82tGAIKPNMSAlB4MjOySP/gqkzN,iv:6me2a7Q3Bi7QX8inai67PszveoXNH+YVagxufWy8+7M=,tag:0tNTE09MEpR0xRb2BMlGzA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Ui8yWXlkQmc2UDhrQTdh
        dHBFZHFHMEVBTFBEUlR1OU9tVUVEak0xOFNVCmtSaUNuUFJvWW1IMTJJNytrdTBF
        M0VOU000eXlCKzZic1E5YzJSaEk1bTAKLS0tIHErVmlNbkNJNkMxWW1WSkRVUC8y
        aHhxMFBqU1ZJUFByQWMrTWFMU0thVVEK1jGtC7mQlm/Aqq/liVzwzAIDjqcxqI+o
        f8yyM3PdH/ivhFhx9MyjJJnpNYVTyrez6MRo5cwqzLIqK1rlEEMQpg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ff26etr9n8nsp2ve2lkh7w4dqd9g9m9u3y8aw77ureu639mrfatqmuqnhv
  lastmodified: "2026-05-20T16:57:07Z"
  mac: ENC[AES256_GCM,data:qD71jpio68VYacOEzs6FlHe0eWgHyeBUdbAgsE+DoIMqvQ6Pkzaq34+tyvBfGtP4ZKuq8tUJ21fflf3IDhKWZR1ji4PyK7JrEyZOvR6QLHTFljRWKn5l+0NQ3jpnh9sCDzSScywCAhag2Nc9mHCYRNMreGGoOs7S+aEypN43NiE=,iv:Q602INuy9NczJ9leqHyAOVjUedS8pGFAeyW9L/Mtbe8=,tag:0Ombya5bO4SujtRgniJB2g==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
