---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  namespace: backups
  name: s3-secrets
spec:
  secretTemplates:
    - name: seaweedfs-s3-config
      stringData:
        seaweedfs_s3_config: ENC[AES256_GCM,data:NP3ykip3rijeHeVaX/80h0dmOf0WbTtohWaI2tmf8hz2gDVCUhVPtRpxVnbdBCFaFNLolVn1THWRRzYyGD6xrnn+CKDXml4kzgIRuSvfIFj4/yyr8qaR6UmrTlxPccUl55MYKRqIMUXXeklomaH52NkV3P5h4a45yOZouk0welDCfZgERK43Ens/Fi+sQbSSaykO4EgkQNqONsGH+QcMroRIptekn0xkJIZgTsEquJs1JbGZcwqox+3iuC5tqmeqVAkBQ5Fa9BHqVV05/cSTZ+i1s7XfJAcufHxyfS3oGbcf9XudKzfHE7wtzL00sDjUsUFfFTgqJpBrbVNYNTUfOy+EsCVrJQqqmu4mc8pcbAZkW+w0tSiB+iYMiCpiBD1WPXPQ5Yej5ZgJwts1,iv:zN9iTOTHNt5gyce2blbo8JkF3bp8WOQG6GJTBbsnk6g=,tag:yjXxHnac4AnWlKYXYhhoRg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxTmFNVDdFV1B3SzZFcXBI
        RW9WeVNIeisxTWt1RzFFUmJTMlB4MXArbFQ0CktsdzdVcWI0OFpwUG83SWhjZ3pK
        N2RaOC9aYXN5NWdXOE1vbTdXcXh4VUUKLS0tIEtPTUNMb0RaQlZHQTFGZGdwblo0
        dmJWMTFxclY1R2czZXJ4ckkrZGc0STgK1O0lh9phkpOSwGy4l9VBq1+y6TgTJbau
        Sxkk85DLgHtZbLIgUCsaZrD7UdkhbFL+44l1LX9lP3JJE+tlUS5HtA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ff26etr9n8nsp2ve2lkh7w4dqd9g9m9u3y8aw77ureu639mrfatqmuqnhv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-25T13:50:25Z"
  mac: ENC[AES256_GCM,data:ufX/NIDFTIHrjSqTrcIf+dCFP65z/d+kKkPELg1d0n7Ij6H2eb5x0oNSbW5mT7jeZ0oa3OykJtyTq+xolGMyrVctS9D40YuXWSVPIQZFL1/8y7AGjQiSO2F4phyiS3VRN8KZtLeWOaTg4BKGK7acQB7dXAX2sxS8UknKdmeUAUY=,iv:FeviP0O0fW+LW21itg2Co8qStY4wHe/tm1Su2Q0se9c=,tag:v3qwTgr/Sq5CO6xtwnbN1g==,type:str]
  version: 3.13.1
