---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: backups-secrets
  namespace: backups
spec:
  secretTemplates:
    - name: restic-s3-credentials
      stringData:
        accessKey: ENC[AES256_GCM,data:pbQvQuGS1LGnqWOUIsACP3sQEXk=,iv:qjPbFhE8CwTAqRKm1783fEnVf+4CjPEyD3EETaPuKQs=,tag:l1n7uoyBa5lLreT07dV1CQ==,type:str]
        secretKey: ENC[AES256_GCM,data:j/w95xR7/Z3g7QZrWcjqjIlWEHKGZyJrQa96mcaoC/l0Jh6As1lG/5A3,iv:igG5Gj6ExAZdt9U7QCsRvgPIN0AYyVuOGAELxqG3w88=,tag:LQDBWNm/V213FKL44tOy1w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxRGMxOEhqRmNTY2JVUC82
        anFpdTBnWjg4TTJ4NGRDKzZOQW4yUHVkenkwCkNTTndGbDZ4cHAweTJOY1JZMXZp
        YTkydkRKVWhEeEFvTlU1TXl6YXdhZlEKLS0tIDBINGJkR2xiZkZsVFZzN2hJT3Bv
        dnl3WkVCSEo4VlI1ejdrSFQ2NCtEakkKVTD7TnzdaTNK8hxCFkQ4cljpTVY+D/fD
        6aDjnKseWsooUliEAQ2HWfSnpiVQWItAm0bfTyD04HR/xC3cUFB/5A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ff26etr9n8nsp2ve2lkh7w4dqd9g9m9u3y8aw77ureu639mrfatqmuqnhv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-06T18:44:38Z"
  mac: ENC[AES256_GCM,data:vyQYz+hduyxMYLT47fAHW+tknAp2iZCEJp/uWw/w7E7CJTZ+hOzF63u2QF3ovYkVutdFV6jf7nmpdECcFn+FdesCI9zX/djZgWwFyD64DSLdlcCAo2LUnAGPCv+B6fixU5lOlDgy2dVROkcE/If5GEhQxj+dxRmLvoZZ2pmY4aM=,iv:xEjnPDGwGiL+dpAj3qKOtkRqDRxdtULFJqa8vFbzyjs=,tag:AM2WI7e1ys3zZvVenJO7Og==,type:str]
  version: 3.13.3
