---
kind: Deployment

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault

deschedulingInterval: 5m

deschedulerPolicy:
  nodeSelector: "balance.kalexlab.xyz/pool=default"
  metricsProviders:
    - source: KubernetesMetrics
  profiles:
    - name: default
      pluginConfig:
        - name: DefaultEvictor
          args:
            nodeFit: true
            minReplicas: 1
            podProtections:
              defaultDisabled:
                - PodsWithLocalStorage
        - name: RemoveDuplicates
        - name: RemovePodsHavingTooManyRestarts
          args:
            podRestartThreshold: 100
            includingInitContainers: true
        - name: RemovePodsViolatingNodeAffinity
          args:
            nodeAffinityType:
              - requiredDuringSchedulingIgnoredDuringExecution
        - name: RemovePodsViolatingNodeTaints
        - name: RemovePodsViolatingInterPodAntiAffinity
        - name: RemovePodsViolatingTopologySpreadConstraint
        - name: LowNodeUtilization
          args:
            metricsUtilization:
              source: KubernetesMetrics
            useDeviationThresholds: true
            thresholds:
              memory: 10
            targetThresholds:
              memory: 10
            evictableNamespaces:
              exclude:
                - kube-system
                - system-upgrade
      plugins:
        balance:
          enabled:
            - RemoveDuplicates
            - RemovePodsViolatingTopologySpreadConstraint
            - LowNodeUtilization
        deschedule:
          enabled:
            - RemovePodsHavingTooManyRestarts
            - RemovePodsViolatingNodeTaints
            - RemovePodsViolatingNodeAffinity
            - RemovePodsViolatingInterPodAntiAffinity
