---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana
spec:
  secretName: grafana-ingress
  dnsNames:
    - grafana.kalexlab.xyz
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  annotations:
    external-dns.kubernetes.io/target: 192.168.10.20
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`grafana.kalexlab.xyz`)
      services:
        - name: grafana-service
          port: grafana
  tls:
    secretName: grafana-ingress
