---
apiVersion: v1
kind: Service
metadata:
  name: external-dns
  labels:
    kalexlab.xyz/app: external-dns
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 7979
      protocol: TCP
    - name: webhook-http
      port: 8888
      protocol: TCP
  selector:
    kalexlab.xyz/app: external-dns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  labels:
    kalexlab.xyz/app: external-dns
spec:
  replicas: 1
  selector:
    matchLabels:
      kalexlab.xyz/app: external-dns
  template:
    metadata:
      labels:
        kalexlab.xyz/app: external-dns
    spec:
      restartPolicy: Always
      serviceAccountName: external-dns
      containers:
        - name: external-dns
          image: "registry.k8s.io/external-dns/external-dns:v0.22.0"
          args:
            - --log-level=info
            - --source=traefik-proxy
            - --provider=webhook
            - --source=node
            - --fqdn-template={{ if eq .Kind "Node" }}{{ .Name }}.kalexlab.xyz{{ end }}
            - --registry=txt
            - --txt-owner-id=external-dns
            - --metrics-address=:7979

          securityContext: &securityContext
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          ports:
            - name: http
              containerPort: 7979
              protocol: TCP
          resources:
            requests:
              memory: 20Mi
              cpu: 1m
            limits:
              memory: 100Mi
              cpu: 50m
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 60
        - name: external-dns-webhook-provider
          image: ghcr.io/alessandrozanatta/external-dns-porkbun-webhook:1.0.3
          imagePullPolicy: Always
          args:
            - --log-level=info
            - --domain-filter=kalexlab.xyz
          ports:
            - name: webhook-http
              containerPort: 8888
              protocol: TCP
          env:
            - name: PORKBUN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: porkbun-secrets
                  key: api-key
            - name: PORKBUN_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: porkbun-secrets
                  key: secret-key
          securityContext: *securityContext
          resources:
            requests:
              memory: 20Mi
              cpu: 1m
            limits:
              memory: 100Mi
              cpu: 50m
          readinessProbe:
            httpGet:
              path: /healthz
              port: webhook-http
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: webhook-http
            periodSeconds: 60
      securityContext:
        runAsNonRoot: true
        runAsUser: 65535
        runAsGroup: 65535
        fsGroup: 65535
        fsGroupChangePolicy: "OnRootMismatch"
        seccompProfile:
          type: RuntimeDefault
      # Requires access to the Kubernetes API
      enableServiceLinks: true
      automountServiceAccountToken: true
