---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: external-dns
spec:
  selector:
    matchLabels:
      kalexlab.xyz/app: external-dns
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
