---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: velero-alerts
spec:
  groups:
    - name: velero.rules
      rules:
        - alert: VeleroBackupFailures
          expr: |
            increase(velero_backup_failure_total{schedule!=""}[1h]) > 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Velero backup {{ $labels.schedule }} failed"

        - alert: VeleroBackupPartialFailures
          expr: |
            increase(velero_backup_partial_failure_total{schedule!=""}[1h]) > 0
          for: 5m
          labels:
            severity: warning

        - alert: VeleroNoRecentBackup
          expr: time() - velero_backup_last_successful_timestamp{schedule="velero-daily"} > 172800
          for: 15m
          labels:
            severity: critical
          annotations:
            summary: "Velero daily backup schedule hasn't succeeded recently"
            description: "The velero-daily schedule's last successful backup was more than 48h ago."

        - alert: VeleroRestoreFailed
          expr: increase(velero_restore_failed_total[30m]) > 0
          for: 0m
          labels:
            severity: critical

        - alert: VeleroBSLUnavailable
          expr: velero_backup_storage_location_available == 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Backup storage location {{ $labels.name }} unavailable"
