---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: velero-secrets
  namespace: velero
spec:
  secretTemplates:
    - name: velero-s3-credentials
      stringData:
        accessKey: ENC[AES256_GCM,data:AuBoHjm45brPVcwZXrbQJ7IBYLhV,iv:Aq30Qs4A9pXNcupp5iG+0Xu+eqt9aTNElkfuZ7Hwrqk=,tag:g6jMS9AnPgcmNt56WkuLCg==,type:str]
        secretKey: ENC[AES256_GCM,data:ASISKEIDMuwcLNQ9u4B9f163DUQvMLa1/DEUY4VDYQLXBf8B2gXBpE7j,iv:bNMI5U2i4Gp8689by64neo50eHeWgCj5cja1rHoKrGc=,tag:jCRcFNrCBDE6lMQWoCp/qQ==,type:str]
    - name: velero-cloud
      stringData:
        cloud: ENC[AES256_GCM,data:9tH4QS5q65Iv57mcRlDzFDP4GDbb5ntHZrtOMNOESkafAclOMdywlaG/aUN9zeKX8XUt0lYV867QhThM4MM05vJc127x4TGc5D+M1Jj+AOe9tLqfsIvpabv0Quqc8AH1JBTZ2p+RUS1suO61krLa0V14oT5tCGM=,iv:QgOfc1Seb0W8tKGQgcdM1l7YkyqSWAuCbxMjI86mgnQ=,tag:vHN5cgQb5mooKyoGm2yQxw==,type:str]
    - name: velero-repo-credentials
      stringData:
        repository-password: ENC[AES256_GCM,data:tmneerFJHk9JQNeYwhE2fCP+Gfp+jxv1KQcC6O/Zx0FLVjEafJ6c2+nEfS7lv5e4+LbeGnTJNBuw3tgzMJmUNQ==,iv:ghwBSw0Vh4MsX4rB/gET7lsWsKpdO07bf7/XZp5/7cw=,tag:GePawOzF5BwpkDQHaEocCg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cGYrVC9WdW15bUk2dERh
        QnRuWW1uQkt6bXFpNXVldXUvOGc3R0hTZEUwClR3V0JzcWJ3NWJ4NTcxZUZSa3ZH
        am1tcStKREUzTDYzL2R1WWZiVG5GWUkKLS0tIGU3ODZFdFFSeERQaVl6K3ZFRHpy
        bmFhMVMvUjc2b3A3WDM0cDZHNTg5TkEK2JCalrtDty0FFa73ChtzUgpWuvFewcWi
        v3Yez1+gzAGYqaiXZxCL4FDZcGSa02kccQ9Thi7r1BZkL01liI8rpQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ff26etr9n8nsp2ve2lkh7w4dqd9g9m9u3y8aw77ureu639mrfatqmuqnhv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-09T13:49:29Z"
  mac: ENC[AES256_GCM,data:zEYl9dgeyT1WJggoSgo+kI53RbiMQTD1x8D/7155CS4M14RqyWHBmWXuLYemnG8tUu8XAdw0ULezKHHcM6+NgnE5m1TTlELy2Wr3aq7prA1TANFdNdG+ZVcj1k5PpF7gJSGnvFjpDzH/zGaJ371A4cjGoBoiFx94p9usBZOiyDE=,iv:s7nXzIJVuYi1OzGBGnDi64S02gZQL+9FobWCXNq1NjU=,tag:wCa3HVgLSvxE76kQKTikzA==,type:str]
  version: 3.13.3
