---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: velero-secrets
  namespace: velero
spec:
  secretTemplates:
    - name: s3-credentials
      stringData:
        cloud: ENC[AES256_GCM,data:AXY8q/17N2nnP1iy5hg2ONYbrVGoZ+KkwxB+7rJsuzy6atav1lfs6GZyzPu7ruP1OXYarz0xKE7aDEiRBuIU0WgZyWD9PrCtTsv6VJUTFEHEXBOYqg0MMjVLcmx5sIZ57MDuDyMTHff/ZxiTu4QGDba3VnJIPbswjV/otBh566WKqH0/qQEfjAQtnfHehP7krnA=,iv:RwJEitMvPSID9mgxghTruO2NLJYiWe+tYVkYDSTIyOY=,tag:A3A1DYje/Biezv0DrZO6Ug==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SDd4VEd4WVJSUzFOTHB1
        d0tvSlNWNUduT0VUcWw1M3dTNDlEV0Y4TEJzCi9wS3VNNWp3Y3luWTUxbXIzSGxp
        YUtjL24zMHA2Z1dNck1zR0c2M3ltZjgKLS0tIFlDMnRtaFF2bWc2SHYrNHdGa1pH
        bGlhSTBaOUYybUlUR2xkSVF6N21XYkUKUr9tloN+n5hwhW7RvmHmel0TH8RA+b3V
        XCoiFzKEVERBSsCpdZgQcyLfMfE0Dos4esq2enkzE0sI++YQYbcGWA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ff26etr9n8nsp2ve2lkh7w4dqd9g9m9u3y8aw77ureu639mrfatqmuqnhv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-26T17:09:01Z"
  mac: ENC[AES256_GCM,data:13cF/4XW1LeqY6hJ1j2fVa1ZOH3h9RM3p2U15hZL8RBehEn9m5swzTmAjmoUhMSz8AQXHN4n6P9K94qXIUvGOa2Pqaeuk9AmVZXIAggyPX+0Adt+VpSM/xshQV9vWWLDe9TkD14oCOxwQKSRSV3/RWA5BGiky7Z4CN1E3ShIxQY=,iv:xL1KBZxMwGlOQOZnt++dFhWqDkRkqSCSqxlBP/g/Jjk=,tag:JZrDHZp22ODgXxceZ6Q/0A==,type:str]
  version: 3.13.2
