---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: velero-secrets
  namespace: velero
spec:
  secretTemplates:
    - name: velero-s3-credentials
      stringData:
        accessKey: ENC[AES256_GCM,data:3iGLGjQ/Ec8xmEcIOEsg/tKm8ITB,iv:HSG0D8YhMDjdWfj9x4CUl4Ho0FHgm9b57HkSJcYIMEM=,tag:ynJUzGvmZJEPOpKUPeotSg==,type:str]
        secretKey: ENC[AES256_GCM,data:gJghRHl5i8lZFDU9Gnr4MsipZFyPaFKB5RttDweOF9BWD8BiIu61K74H,iv:+tFeHwGGovQES1qdZYFV0UdKlafxwV8L4xfRtvVM0oo=,tag:QAa87DXgPnR0gBUOa1M0hw==,type:str]
    - name: velero-cloud
      stringData:
        cloud: ENC[AES256_GCM,data:ugsEmLT1WpG2vUTRUQiU9fDgqU3xSizsUissEcQ8A7OIe6ElIUIFIEgiWWjNzl1XOMzvoTbmzZ/6CB7SwO76e3WZEolQLiAZvNPbOW3uw4Kj8671bP4BgY9NrNYFFSkVH2aA89C1Y0Yvj/REH3fdN3qiXUxMMcU=,iv:TWhvCRMYlVpGVz0Qbj5Nt+kLxqg57nAT+v8fQPqNZAc=,tag:w7PYP1YKmSWzesaTyzwmzw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVNVRpSnRvdGxPY2RseDJ2
        dmxRQXVHQ01nV2lTZXNNY3BOTFNQdCt5WER3CjRrOUdIaFduUG5GT1pFOE5KZUZM
        bXU4M3pRSnkvOWNwQzBEeTkzNk5WVWsKLS0tIHJYYUVudEd4TE1HdCszNmQwSWo0
        YmJOSTJMR0E4czZ6aDR3aFM5bE96MU0KZ6kWmQvxv2blWj7MIImxuO6lvdPUec5j
        R3D69ESjupLQ9lt+a913Tn8X1O+f7tTigy7nd+WTYI10nE8T7iOhww==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ff26etr9n8nsp2ve2lkh7w4dqd9g9m9u3y8aw77ureu639mrfatqmuqnhv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-06T07:17:26Z"
  mac: ENC[AES256_GCM,data:ZQd8djdWunZb92mfiS1FfRxKpLSo8n6L/e4iVXqJSvsXR+UH9qIHCx5Bk07YWxvJfJY3MlMzfi4LoKdQ0HQObQjlIyhXeyo1RjUM5QrR4ihbieYKRW5B1LV41TEC6stfzVbubirgBLbF+nXOu2c+GfdxIMOn6FWhPn4qztjw/rw=,iv:AF4rxJltFcxj8IBptwHzSfVhfCNYJmHz0rayrS5X+NY=,tag:JdRDh1rwC4Nl9JTYOqliwg==,type:str]
  version: 3.13.3
