---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: monitoring-secrets
  namespace: monitoring
spec:
  secretTemplates:
    - name: alertmanager-secrets
      stringData:
        admin1_chat_id: ENC[AES256_GCM,data:iRPZfKUndcJWRA==,iv:QOmJGtkgx8siWNaoIm9pGB8tk34iJnM31ny0tb6gJZs=,tag:CwYdVFDyg+epXd9dmVpInw==,type:str]
        bot_token: ENC[AES256_GCM,data:AlmxZb8qk1IrLQuXdfPBNMQHHqPZWPMTod6cTq77zcKc4mjTB6IqmZwGnQE2Cw==,iv:JSVdkQjk1fkYzZ8HwkscesfSlP+c1/4Oz9ThKIgmfSA=,tag:z0lkcwJqM258Q02/idxBYw==,type:str]
    - name: grafana-secrets
      stringData:
        admin_user: ENC[AES256_GCM,data:LbpJgRk=,iv:DylGXn6Q1a1I9jBe355KD13rhgvhTUHMjFaUqcYqjzQ=,tag:A6oCIIlxMF1x2v2TikTPQA==,type:str]
        admin_password: ENC[AES256_GCM,data:PtLf2K3y2ps6qaZsGFBbEBBTsynyTxbMYYoEkMBaLN4Q9AcT547/yHjQnX9JemAw3c0GhOqcJTpvG4LkWdiCEA==,iv:PzbIzG/2oOJPVySetmpl9PzYIJMFssn8UqUQcDuN3rg=,tag:I8asMzltp/z87FMFMZVMRA==,type:str]
        generic_oauth_client_secret: ENC[AES256_GCM,data:i+oeLbb5lKjI0xDCJHhFOZWHteDsT1kiBV+Fpm9DCKvC8RUmMiO+cKbBpwk3RY37r/A4O5g1cUfp4A7f+Ouf25eOEdZs6CtY2OTyS1nPHlpPvQDGXZFyS5D48svG1NfXlamyjOfpkEohObWMet5kXi8D7k2jODFxruIS52zr+Vc=,iv:nR7oUi6L/eolzL/fEugt6ea7rahMVC32qZHoKUxGH74=,tag:YhzXzOpYOKtV05ImLeASBQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwNW00VGlkN3QwUGM5Vloz
        TnErVlhtT1ZOemdTYURtMEJMUmRYVGpqYnpFCm15azdnM213L3cyMmxHelJhaHVh
        MVRETUhpZlM1YW5uS0o4Mk1SZGtnRG8KLS0tIFRXWUFKU3o5bnRacTdXVEp2Y3BL
        bkVoRTFZSmtKby83aU5obWdjK3QvM2MKRfImMbQimP3mZH01j3ziJNwxTiH+SuuX
        +Cq23SOxad0Agn+z+5f2IPHwjVfDkTjChYQS9eOoapzI749w/W5L9w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ff26etr9n8nsp2ve2lkh7w4dqd9g9m9u3y8aw77ureu639mrfatqmuqnhv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-30T10:37:29Z"
  mac: ENC[AES256_GCM,data:g2LHxgHj/ayVOc66Crlokcfnhm7whwrknOrnvpzR+Rfv6Sjk1kr5hfhcCXWiJAzzrH5NztPcf7OMzYSeh7eJx8gE2Kg15NoZVK7Ibw1sd3qOkLeBoALPpd9w8bCJebilW81M1S0LBw+TmRvfC+8LhrqdGm2ORfnh4HEgsdL/94U=,iv:KjcWmlPA3TGCm1ODDD2Kspbtpr8u3gsDVPquJjxy+q4=,tag:n+5jZFkRQUFuEOqUDXUEdw==,type:str]
  version: 3.13.3
