---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: monitoring-secrets
  namespace: monitoring
spec:
  secretTemplates:
    - name: alertmanager-secrets
      stringData:
        admin1_chat_id: ENC[AES256_GCM,data:zWk/Z3PaVh9C2Q==,iv:q94zBeF3ezMYRPirRkvNDYa1EilT9SLBgKTxrMLb6f0=,tag:G7U1tpNtlkpLSV6eDHAocg==,type:str]
        bot_token: ENC[AES256_GCM,data:UgCBKNhJy6+GrOmuQvfNYyEyG0OgS/Aq0on0DgBa3SwZu5YCS6NjJF4/Ru2UNQ==,iv:86Ypxgdw7R2Q5GeUcToixlMkHcwj/g++/qPfABU0k7w=,tag:2iysXCr6K1+Ea3OEN4piiA==,type:str]
    - name: grafana-secrets
      stringData:
        admin_user: ENC[AES256_GCM,data:4Mmp4tM=,iv:7X40FUneiYylnHbCgA3IrkJOPMdnMp16erFdEX3pgPo=,tag:9hdFibCsrAJIoOGFvcYHHA==,type:str]
        admin_password: ENC[AES256_GCM,data:rFtoPBz7JMPN/S+HVuOOjHANCrF5VcvOHz/1r9xGmcqyZrtcfrq4p4odDlyVGyowZKJFC4j/kg00c4x1XEDJmA==,iv:1QbOQ8MyF6MEc0edqY2p6yswgWBqlS8tLet5mhWuizM=,tag:bAyiqRfyJpg7ZYBYsirE9g==,type:str]
        generic_oauth_client_secret: ENC[AES256_GCM,data:kZFRoMSo8HHbgj3LbA4yHGCEQ5o5UDX6jgSj1gctkPGfw6z+pwB86v0omqqQVvbK+qTYVo6rJHJhbgtj5zsgwTaCxFcx70vH,iv:QdUp+7AVL09F9iSgE5fmqHkomJ8gPMrFip72Pwkigxg=,tag:k51VdVZiYM6unMotRfNAIQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYT0pZcldtK1BraEl2cUd4
        NERxbmhQTTBsR0VSVE12aGZIUi9CcFkySFE0CmlIWjgvOGhwVVU2dmRrVDFCQVI5
        OXhRQStRMzJtWGE5TjlTS2VSRnI5V0EKLS0tIFYzdVdCV0pLVUU2dWxpdFg5UnI1
        RXFwaGk2Zys1c1RHbVM1Q3hubnhhUFkKgeaZGOaCb2xRk0BBNFIo4LnP3ZQ++ZrO
        xNBfbf6fPnFKlP2BcDSv0xMo041ljqErjkvIJ9XKtWIKcesMzvNn4g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ff26etr9n8nsp2ve2lkh7w4dqd9g9m9u3y8aw77ureu639mrfatqmuqnhv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-07T05:53:41Z"
  mac: ENC[AES256_GCM,data:G6a7Y9DpGhuAdqMMHzJvThUggze2nW78OvkLtLVgPJcSvmJW5+XP8sIThXoSkoODfefWqMJy8l0Rq04z69uFGMyTcNphCzTjWoAHw6nk9w5VV2yRmCxPE6go6TppvFlD0kIjklKW+HMQE2TVLch4MNq0CUA4XFv8IJdE3rICNFo=,iv:f5cHbo17KypN6V4ZJb0UFJS0EWcdrdwN3GdGBYcyldo=,tag:2wUY1fqMxAMwiY+vwpzXRQ==,type:str]
  version: 3.13.3
