---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: monitoring-secrets
  namespace: monitoring
spec:
  secretTemplates:
    - name: alertmanager-secrets
      stringData:
        admin1_chat_id: ENC[AES256_GCM,data:dNAbXMU9YQHZJg==,iv:reCDKr92iRzvky9a8VccXDhzIr8y7opbZk1Q734zMzE=,tag:CJ47PoDIcDSpvriRjbYkWg==,type:str]
        bot_token: ENC[AES256_GCM,data:QdMDgO03M9DtM1RtipIdC7DewPzYONpWKxr83X+EqQ7rUGQN4l25rf+9FwYm3A==,iv:I9KS20OL75Sm4RcAUTU3VW8dIfgSJcdZVzIfK1jdt+Q=,tag:Wyo9VYPniWlqxFaWkoGqWA==,type:str]
    - name: grafana-secrets
      stringData:
        admin_user: ENC[AES256_GCM,data:KVSvHVU=,iv:uMgkU6QsrhmJy73irrYQJ5WcFwah9F0sqsmmf1m2ZgY=,tag:zZ6jqtSOrjA3ffNeRuiVCg==,type:str]
        admin_password: ENC[AES256_GCM,data:X/MSEnxMUh3XVVwCoJHoqMJ8vBKatExItpM+C3XLuNnejaAtWuJWmOSLB8fE4+GM9D8rZGMIjdsljl/SMIde9A==,iv:WNfiKbmMqweGuScH3Wjku6KdYMnM6473PKboASlnrAc=,tag:DTiIBx4OvZee7t1tOLTAcA==,type:str]
        generic_oauth_client_secret: ENC[AES256_GCM,data:SMTQmlEWBA9/IopoZGBX3PTxqQZjzbQiwdIQGLu19heciTsxSPB3LLyAI5AFnDEQid5Lomhkgu8OkR/rBQL++jch2lcWwU4C,iv:RLYNVLex5Trv+HRC8RVao63zxJb4Fl8vCPZcGEqGjTA=,tag:UP404CSYX+MO/AwKXbh75g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnQkk5Ui90Zmd3ck5lbWda
        S2xsSEtUY2V5YmVXV2hOT2loeEpGMmJrZTNRCkp1N2FDbHlldmwxc1ZaS2tVQ0U3
        WXptM3MvYVNoYmE1SU9zeEdKRkJNa2MKLS0tIHNhMDdsWE0rWkZ1Mzd5NlJtZmFZ
        TDRuNWRVYUkxa3FySXFId1RUaUdGMG8KsO3fXV+O44VkKVy9XHoVR60AIP2U/O7E
        qBhUeOmH9Gl5dt5CJim/j7DPV2NYGXJRRyxgxfm6tG9mPcUU3VOaVQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ff26etr9n8nsp2ve2lkh7w4dqd9g9m9u3y8aw77ureu639mrfatqmuqnhv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-26T16:52:05Z"
  mac: ENC[AES256_GCM,data:dr7ArINGyU7R2gOZotBRTRSgWbt9V9K6yzSDzOV5FJrWWwih4b3abl3GrHgu27WqSpo7YaGNxL7YYzfAkTvKattBjJAuIoq9y7h/ffDrAAE2cHv0z2lvZVrFEJnHX2yyGtMjiuRp2t3sTp0XBZ7i8H537M+E2GyQJ212aYda1YE=,iv:yJKw5PTaffOSkf8A5A1z8NmgDYXhAFU2aeGWRqPidoY=,tag:yP6wzWCcEghlLigUKvSqWA==,type:str]
  version: 3.13.2
