---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: device-plugin
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/AlessandroZanatta/homelab-v2.git
      targetRevision: master
      path: kubernetes/misc/device-plugin
  destination:
    # TODO: migrate to its own namespace!
    name: in-cluster
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
    syncOptions:
      - CreateNamespace=true
