---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: egress-vpn
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/AlessandroZanatta/homelab-v2.git
      targetRevision: master
      path: kubernetes/misc/egress-vpn
  destination:
    name: in-cluster
    namespace: egress-vpn
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
    syncOptions:
      - CreateNamespace=true
