---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: etcd-backup-secrets
  namespace: etcd-backup
spec:
  secretTemplates:
    - name: etcd-backup-secrets
      stringData:
        AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Aj1Biw2DlZtmlOiSGQsLUNTidyBu/szMQRg=,iv:GZEW2yrB/KF8FiERNeCgIcerDxU5eZR/WZi4q1FE04Y=,tag:e7rkIcsQcLsQeHfrBHoYRg==,type:str]
        AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:6nM6j/k/PPvf8UzNx+gNrmOASJILVBMz5VABBCp1FgKB25tX2+/+dAR9K49LumiVNFoeA4taJweVzaBL9bXxQA==,iv:nYx3y+xlZK1SJh/4LQw/EnuU609aw7CqD6aCziM9SEE=,tag:cEXBQANwCRfHZnMhknUzhQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhQ1hWeTVxTUJDNDZKUGU4
        K3Q5ei9mWWhOMEx2ZVR6N1gvNjZvRlM0MkJVCkRQSWp6NkcxazFISXJUVzhveC9I
        MVpQMmZDSFZhQVhsNmorV21EcnZTZjgKLS0tIDJlcEJBVVJwUmZnMXdzaEVhYWxH
        b2tPcGNicHpMcjZ6WTBKSlVoc2g4OFEKlzGJNhaBlws0boTh9c0OYSAVEFI1FaKW
        nETRGKceK1j9UvQwbYyTskqikS9xajRKQPeNhyqeZVWI62yu23m3Hg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ff26etr9n8nsp2ve2lkh7w4dqd9g9m9u3y8aw77ureu639mrfatqmuqnhv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-03T13:14:21Z"
  mac: ENC[AES256_GCM,data:mB2cCtNNSRqpy6wPtp/9ZWwxr7upj4fC/upyCN8qPOy95nCSRKxKoXhfV5kMyHf9oZAAC4GfIpOuQbimhfT0ls3OAq/woSSc9fm3fK3HfV8KjMsuddXyfaFSRQ+TtQNKq6BmE8HMLOxpy3kB41fiyuiAodw0u0iQrGkAM/ruHUM=,iv:6MAYSnfA8Olx3nCteTXxvhU4iKKbjye4cU0paoKwrsg=,tag:oH6NEo8pWLPVGe5odHiMkg==,type:str]
  version: 3.13.3
