---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - network-policies.yaml
  - conf.yaml
  - secrets.sops.yaml
  - uploads-pvc.yaml
  - cluster.yaml
  - cluster-backup.yaml
  - valkey.yaml
  - web.yaml
  - worker.yaml
  - ingress.yaml
