---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  namespace: glitchtip
  name: glitchtip-secrets
spec:
  secretTemplates:
    - name: glitchtip-secrets
      stringData:
        SECRET_KEY: ENC[AES256_GCM,data:ag35qxou6R7bgpqL3wrhmpTvbZjJy4Qzxpp7Zoc7yGmEJnETYsDV5o98hv1e9dEvqVFU1rhl3LpcgvT1fixLhQ==,iv:gkxdPLy+7zgLdYenfJ1kpRMJkPu0b1xyXu4SLjAeZlk=,tag:Mc0vw4FB3WMaixK41d1zHg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2MWU3dzBYejU2K0xhdktq
        TFRVUklYMHZSMjNCdjBrVjl3TnNuRDA2cHdzCjFoRUZTQmRTZWNTSW5NeFBkYlRm
        b0NWYzJBZUk4Y0xGekQwS2kwZ241bzQKLS0tIEtHTFZqVHUxekRxSWo5UURCclpO
        czJlVkk5YVdsNW82eGFWaXhpd1B4bjgKpyrnilCtLuuLBzGdD3w5HCtrPzCBsBs+
        +yk0JSuZvkw6xqAUjIqUeWusJp4eR9Zuix0uxy5Tq475Vb5Yg/c5vg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ff26etr9n8nsp2ve2lkh7w4dqd9g9m9u3y8aw77ureu639mrfatqmuqnhv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-06T12:09:21Z"
  mac: ENC[AES256_GCM,data:wfheUth5MjtRopT4j+9bjCWUrhgfQ2QOEx/JdfDUYN6t1v7h4wVhkUJb7oRlr0yvm2ewRZBabJwN5OfR6qN2M9W1l3aOGQ6oCeF47gwSAw3+VXxODxv5VSnTtPeXhIYfUhDTy7AVo5dBjDZz6z3fOwlty6FuBHnG2UHz8hOOrfs=,iv:Qjs1+ODzBOoTh44MAggiVetsN9UPtFnm8m9nGRBxj3s=,tag:22Ml5YNhm6PZ3S55y7xsBQ==,type:str]
  version: 3.13.3
