---
apiVersion: seaweed.seaweedfs.com/v1
kind: S3Identity
metadata:
  name: vaultwarden
spec:
  seaweedRef:
    name: backups
    namespace: backups
---
apiVersion: seaweed.seaweedfs.com/v1
kind: S3Credentials
metadata:
  name: vaultwarden
spec:
  seaweedRef:
    name: backups
    namespace: backups
  identityRef:
    name: vaultwarden
  secretRef:
    name: vaultwarden-s3-credentials
---
apiVersion: seaweed.seaweedfs.com/v1
kind: S3Policy
metadata:
  name: vaultwarden
spec:
  seaweedRef:
    name: backups
    namespace: backups
  policyDocument: |
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Action": [
            "s3:ListBucket"
          ],
          "Resource": [
            "arn:aws:s3:::cnpg"
          ]
        },
        {
          "Effect": "Allow",
          "Action": [
            "s3:GetObject",
            "s3:PutObject",
            "s3:AbortMultipartUpload",
            "s3:DeleteObject"
          ],
          "Resource": [
            "arn:aws:s3:::cnpg/vaultwarden/*"
          ]
        }
      ]
    }
---
apiVersion: seaweed.seaweedfs.com/v1
kind: S3PolicyBinding
metadata:
  name: vaultwarden
spec:
  seaweedRef:
    name: backups
    namespace: backups
  policyRef:
    name: vaultwarden
  subjects:
    - kind: S3Identity
      name: vaultwarden
