---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - network-policies.yaml
  - secrets.sops.yaml
  - cluster.yaml
  - cluster-backup.yaml
  - vaultwarden.yaml
  - ingress.yaml
