---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  namespace: vaultwarden
  name: vaultwarden-secrets
spec:
  secretTemplates:
    - name: vaultwarden-secrets
      stringData:
        ADMIN_TOKEN: ENC[AES256_GCM,data:mbz2O7Dzm1cCzeRMwlwO+IZSENhp5C0fIBGAbpiu6nYf8+ohXoH0uxhfxOaG7S2PR8hUK1QhGmEty2QtbHOfTw==,iv:jhANGvASeZhE1IIIZm/QYaGGPnOn3mRV9OiyVCzz89s=,tag:qFUobmZd2xvzO6YTTuD1EQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByNnJ4bDZRYzAvQkRIYjlU
        TTRFS2d4UldJaENMcEVFNkZDcEZvTXVCb0hBCi9IY0lSamQyb3lBTGxwR3RxQ1Zl
        bHNqdlF6bUZJKzEzbmUxdjRRVUNVeEEKLS0tIGc3eFh3a0NDWldZOGZ2R0xJRFBt
        L3lEVFZQblI2WEtOZFZUVkF0ZjRLN1EKTPtUC4Ha8WObKjTMT9sRnWfNaRC+4JMw
        ZP1mm/DbgTwRUseTryMNBS56dMuB+BPiunRYkYl6RuUhDk4klnsQdQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ff26etr9n8nsp2ve2lkh7w4dqd9g9m9u3y8aw77ureu639mrfatqmuqnhv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-06T12:00:29Z"
  mac: ENC[AES256_GCM,data:9ugsbQqtAInNU3zhJeP2uVGSlMYbV8gPZo38kKrz69tNzFXRp1o6ir6xW7LWFF3zSl9z4Mrg/TNP/uaOr1LpG+ir13owYFKLdUVB61n3NlfuF2XoQmf4VPlvMC4LZpiF37q3o5itxm0IsSsTNi0ybXd8qZPqGTu3NwFxLyR8epE=,iv:Cs0ykNzs+GCYr59Knc64AxSLOUxnMX1onSU+IIR0qS8=,tag:e8AVZuJuZ+wnTM//P11b4w==,type:str]
  version: 3.13.3
