---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana-operator

helmGlobals:
  chartHome: ../../../.charts

helmCharts:
  - name: grafana-operator
    repo: oci://ghcr.io/grafana/helm-charts
    version: 5.25.0
    releaseName: grafana-operator
    namespace: grafana-operator
    valuesFile: values/grafana-operator.yaml
    includeCRDs: true

resources:
  - manifests
