---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: device-plugin
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters: {}
  template:
    metadata:
      name: device-plugin
    spec:
      project: default
      sources:
        - repoURL: "https://github.com/AlessandroZanatta/homelab-v2.git"
          targetRevision: master
          path: "kubernetes/misc/device-plugin/overlays/{{ .metadata.labels.env }}"
      destination:
        server: "{{ .server }}"
        namespace: kube-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
