---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: xprem
  namespace: expo-updates
spec:
  secretTemplates:
    - name: xprem
      stringData:
        JWT_SECRET: ENC[AES256_GCM,data:11zlW0dEbeXkN3lgOXolXbWx+BORqKVd+Sk1WxmFFTDSne2nPaRovgW/cRdOKrr4sC69iBNzNEnCnYcklAKLmA==,iv:5MdGxG2psHApZitqYR+LXNVo/Hcs5K6b8Y5g6+TnGno=,tag:DKdg7ZPkH4G+5/dcyN1g6Q==,type:str]
        DB_KEYS_MASTER_KEY_B64: ENC[AES256_GCM,data:g4aQgP0GQXbd5I+L+fypQtvyEiBFq68uFaOojvoYTeUjUuC/Rlj3epX5b7Y=,iv:9UrGL1U3RS84XGwfQOULmib4gEQeBZWyZC2XX9x00zY=,tag:qt8Ly1vNP2UWEHeJgr2ezg==,type:str]
        ADMIN_EMAIL: ENC[AES256_GCM,data:5cqsciT6xVW8Nxk/2Vm4TySJ,iv:R/p8QVPI9VNsXTtf2eYhUq4kk3JgLEiu+7DLbKEH76o=,tag:83aTa72ZiHeQAtjBfDf8rg==,type:str]
        ADMIN_PASSWORD: ENC[AES256_GCM,data:D279oYR9mmzjFeht8OCa9w==,iv:ucwGQYqeDj2CT9WAP3oKSyjspFqa4TpqGE4Y2dSTDQQ=,tag:WVAAb7HiofrR/h32zds6mw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVLy9ZRkNOaG95T2Jzbm80
        ekNQNnpxajBuaHdjTDRsekF3RnUxR0dIWUVJCk5mNWQ0OG80UjNMWXFTWlZsM0Vx
        eHc1a2xwRXhITEFsMDVZVjVRNFJhRGMKLS0tIDRXc0d6b0FYZnRFcWY5elRNY1F0
        UUo4TnNzSFNqNlZkMXA4RVNPb0tGSWMKNxEjgj86gBfm67mmPOvsKXDz8LbtO1UB
        8siZY3LTKr0J4j+EEdV47ZrPKtYbL2qhGptJYgbo9fi3SWJ/2NU4dg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ff26etr9n8nsp2ve2lkh7w4dqd9g9m9u3y8aw77ureu639mrfatqmuqnhv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-30T11:59:03Z"
  mac: ENC[AES256_GCM,data:waqAgklvNbRTKSV0pdTMFarg2iX4M2hou4fxqVq4icf09SF1yz4fRpPbOYsWCTSBXrUojKIluRP9XC7fufQ81Am9smR5ihufeqMZJygnk/tngAm+OfpEwUcWZD8FSCOpbmhbm+iZn+W3qUkm0GtDnPWYkEgDNYDvmAD94E+Tkfk=,iv:U7XPkgw5hLNZ7rGdN13fPAYkZaHc1113P3UlxFhMzTs=,tag:tp3ItXZluEyavXjwsteZxQ==,type:str]
  version: 3.13.3
