---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: reciept-secrets
  namespace: reciept
spec:
  secretTemplates:
    - name: registry-credentials
      type: kubernetes.io/dockerconfigjson
      stringData:
        .dockerconfigjson: ENC[AES256_GCM,data:PhsbLW18lqKzYm0e2xVomA7318RZc5isS24Sf9GRDY9soElex7OPNZqHsIMEDDtzIJMOM/G7BcGKcYCBalrkkHIytf68avLHbRacsyTsBxAEq5/3FO8WUvmIUg2yfLdxgWbAgGG3bnx+XoUZsGuZxf9KVucPwvya3BcgT/pfxnsS6BvHqozWRWjVNxHRY+aidwzS9rSHZ5Tv0sFyiAfHhwTOajkPt80e8egj,iv:PrI5DvBuLvMeSLO6uo4FDT5H4BWs2bwB5xl6kZGgQvY=,tag:v8Y3VSu67o1ua08LXAcxag==,type:str]
    - name: reciept-secrets
      stringData:
        AUTH__SECRET: ENC[AES256_GCM,data:5FF2TM+TDAG6wh2avW8YucbQGpTFaz2QR4FivdA9camfwvaHOmePA7G7mZk93MfDz4ntX7De57fEOs3HzVqetQ==,iv:tUvjVo2mbmbitwThTlpHixSe8ycuAxIQvqkkpwfNsY4=,tag:9OloE6j4CmlJt5aJ+cQH7A==,type:str]
        AUTH__OIDC__CLIENT_SECRET: ENC[AES256_GCM,data:zTc06jFjpYSDtg1r9W+LAOdbUvLM9frGJwgZU2idmYO1VxksoeUVtG3se2RkuEZtBXrmlhDl/EHueH97K12Ll4i5UG5SgROl+a92I0y8HOgz5k2BHpUVvc2WGGDgXr09irM1DniDT+Dp3y9OyNpKhY5RPkSwUQRQCkSGAdl/EdM=,iv:O48iYS3800lzDNmwU5ybMg1RBkVT8YD7JIbLK+M2tuo=,tag:Inz1TwlA7vfZa33g8jSYMg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpRzdHR0xuQXVhRzhHOSsr
        OVlLbmdHYVFTdXF4bWxlT0c2QkkydlFGTEQ0CmlyODMrcU5PbFBTSEpsR2pWYyto
        MzQ5U1UzTS9sRG5OczJCZG5yT1I5Sm8KLS0tIEMwb05ZTU5VWkNZbGU3eVIyaXNN
        ZzBaZWtSZUpxNGhPR1hGK3RpWkFJVWMKXGN7h6v55w0FrgiLqN5q4rEovL/W+qwC
        yRSBkZU69C5mOuX1V3TO8g8XlW+jaVr9szukLcRWSE8xNsYDcRfDCQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1xulh9knukykzerg98wclqtfx33crk0h30q4jhwuz03ja9nsjppwq7tmycl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IE5EMDdKWXlO
        L3VINzhYYmNGT0p5QnIzNU4zRnpGbjZBRkwvaDdVRERSeC9VN1VNTXZJRHF0NVUw
        ZkFCejZ4V1c5TGVyTnFGZHdTcUYxOXkvZ1FENGRURGpIZHFUdDFhUXVjYjVqN1BG
        bG13VXdLL0x2L21pWVU0b2NITnpEeGpWamJ6Rlg5NVRyVHFNaCtCMExKdkhkakxL
        b0xVVTNNcmVpbGZaVWpGd3Ntb2lqazZTM0xkazN5Rk1ZN1RsMHR5djVGRzB3NlhM
        dzB4OGhaRitubWw2V2VjR0FQa21QQjZFWkZVaVJJM2czNUlEaWFNWWNWcmVJZXVi
        SmxmSzVuVUs4akUwd0Y0amk3dlRnbG9RZXNDcFFoQ0NxMUtWQ0pVUG5EQW10R0RC
        QW0vOXhXa3dWaXZoTk5OSmdkamRlRk9EbmxOUlQ0VFp2WFZWdm03MnRDVDRnd3Zl
        TnpkRTBqRVpTcEwwOUxYeTdzbHFQWThBby91S0Z4SmwwYURtQ1UxUGZXaHlVZWJK
        UW5OR1N6NVJLRU9BczU1RTg4VlBHZks5Y3Exak5DOThNWXFmQzV0YWh2cFJaYjRF
        Wlg1R3k2eG9sdDMxQkZUYmVkL3l4dTZLaHFSY3ZWUWhvNkxBM1ZISmJrWk5BVWJ1
        R2JMeXp6cjk4ak8zbVdpRnIvLzM1L1hFdzdrU1NabnVWWDBEMnJkQU9pWEJ0M0RQ
        cHJ1ZG4zS0hFOU1KdHR0VUhwMFY4RW9xZlQ0YVBuc212MFlyNWtnZmFzREJKMEJ1
        K0NVVk5qZ2FvaEs3NVZHYVF0elpXUExYZ0puK0MwOHRuRlZXM2hvOHBHQngzZlVF
        NnpoSWNHc1ZXRTRjbHZTY1BQK29IUWZRbEt2MG43OHM1RGl4Nmd1WXVaWkwxcncr
        dzliaWRiT0xoMm8rRlBDcUFHWUdYMGxiZklJTUc5REwyRXhURXRzbVpYTVRaMFNX
        dml0WElWajBHTDRVa1ZyMHFQV2lBTitDM3FDM2ZvUG9YOVN4RG9iK1cwVFdwY0pV
        cGRiTDFEUFgzTHE1TmI3Z1ZnNlpySUVnWjRMZHF1L1Znd21MK2VOdENwWXJ2dzJD
        WWNkcWFlczRDR3lSSG9yZHlpcFk2blR4NmVuaWp3Q1F4WEVENTZBbU10ZEhFZXNu
        Q1F1M2VIT0lObkxQeDRsTTMxVDNaZWZWb2lkS3FzK2Jsem8yQWVvVXc1WUw0ZjhY
        RHBzQU1FV0V6WDc3V0lTQ2RwcFBqR2p2RmVnN3BiYmdRRU5GSHdHRjUxZHYrbWMw
        QW5oL3U3elRpK09oZENSelBxVlZjTmNSM1N6ZVR0Ky9aaTRPeWN6ZjdYWnE5eEZ5
        bGZnYlNteEx4M2xZZzRIakt6dmdjUlJwWlpFUjVhZ0RaYmZTZ0s5RU5PMmtMbmZq
        dzBZNTBJWnkvM2pSVUlwM0k3cGExeDVOVFl4MkFNN2JqMTkrNnJsdSt0cXUyZnBF
        c0tCck5DYjNpUmlwdC9neXRlVGtJZmJIQUMyNW1JUS9LVkFxcUN6UC9OTndmZmda
        NWhUVFlWZld3UzhaK3NPZHhPckROTDU2Um10NDZuMGEyNUpsNjJBdVhWMDc4SjBZ
        N1dTcVZqUUtWdjlvTFFSQnpGNEJvUGhRU29VN3VvVHFCa3FiTzg2WTZZT1EzM2RU
        Q2RQd3hJNUw1NlNUdnFqOS9pSDcrMnNmUUc3RVJtekFOcDc2WjREZ0UrQVdXN0ow
        VFVaM0Uwa1BXQkUramlIaWs5SmpDa0JUdlJuWWZ4SGNtUFlYZFBlYzJ1cXV1ZHBZ
        R1NNc3NlY1FveGdUL29zNThpMGlJeUNYWHJHakJNRlNRZy9qM1ZHMk5iaHRtb1F4
        TmxMSnFoaDNOa0krMG1zQ05jd0h5NUdrTEQ1MUZxMmdvNFhGUkF5TktSQmZkb0Za
        T2ZlWGI4MGM1RnQyM29ZN0JpRkgzRk1CK2tTOXZVQnllUlBPaDJBVUJlQ2dRZwpv
        SjByUDM2MXZJdU9rdTZlK0lpN083RDFNUyttREFEdVNjVjBwaE8vOVA4Ci0tLSBO
        VjZhQkhHdk1hQVoxUmY5RFBQeE9DY3F6WkhTK3BsNVRrYStnOUtWVWNzCq/tekpk
        ThZsRhwYANiwFiqI1IThJ4JZeJ3Rr+DfEQaG5jRvHzEyvHUTOomvrDx24r0Ql/YX
        edVaTydQuillbQ0=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq10akgy7tt2gw5j4t9svt5cde2aag9legf2gdf4fxzujzjhxt64nfhq7n8hp4fsryd39sef6cgxathmhkrvgrqccfm2udsklq99wphhcd5tpu6vc2kv35uejsnps655s2ux8nfwvjxfywc2wyznxu2rpsuk90esgud0xsutk327ctr2rxsjd6jcgnuuen6sfvzvqrj0n5kv0u0ck28myj3spz7mfgvprlkkqya2fghc94kn5zfcds9fmyts45g8y8kmw3v964zu6gvvzar3dax4q3zudygxkwtk9tjzs73yan74ngwtv5h0cjanufp7nzqpgextz2an3p9eeugd7trj0aqnk54q9x88rzyaxf5exj90r5uj3gcxj4xvuvpzqttjp4ggrctpw3ftvj7tdfam2gpjx3rapfyz79jjjdqa2fxrpn2njcj4n7u2hduspjqtqh02ytcykfeykl8yuwldpd9va5dapmp4zevhuzywzax82aptspw6gcnjn6nregh9m6zklksxeflvzjy0396c74y3cpg4jveqzlf3fuc98ss0n45t32mzutt9vaygu3cnlzvp2dh3622eqreykw3n24r3tc6qpvyz2wjq38tq8xsgc609rx2fnqt9unnfruaw2xasvcwutree6s4vr799305m9nn4zeuyeus8z2gge9fq5533qud0t98q9acfjekeqdmjq0mvzpus6ucqrq4yeuejg8fdvmju6svl09qkpp5z53cfn8p2wmc2kuzd9tc74m3n4qzyme4e04kcjwpwxvxpuq8lxxrhmgw2h4hrs92nw397tf2875m96quxmj4f2ykyvqugkdp2akr3j890zrsw9d9eaz8zzcvh47yg7080stttrq5wgarw762wna5dl7qh8qay8x0fsnff7gxsv0fejdhclv83xd8f2ah0f2qmaue3xwn0fs970y9ffezy9723hlx85ayzp0fwejhny3cawue7tx43uvpjcfkg6rt3a3jmv2s5sy5s7yyvp4rqkpn634h0j2qccdvrhk6g9ntjqsvmzv65qaedmwmhkr3x26ety97zxdz59ym87lfyy5qrw4musma25nzpx550wvx30s9jmmx5qjgq2tmdnag8xjf234vsyl8hvxmsxdufzg9cxknn93t3fcvc59aqus84vcnfva2s2ntpdzlcx9jg75hmep2j565ymg4j5v8f2v8y3f08pcjxv7v82aje0mr0x3a6je8c3689hqe3307q4ggcp00a9ut5y46yzmqn9dhjug502kzryuh6m7fenrjcxl9hdxehqp7ez5q82szhyuzjwqpku0u9f8sn64gccn6jrr2k573vazj9gflz4p5a8echphmk2vphzwrx7j0mumq0l63ypvt3ulr2dkmgv9zf3jxcewp9879tmj68ghcsy23z2ne7ha44uvyqk5tdj0rwzkx7aje2hchcuz4pm9rypk8zlxcxwu88cnu6g04daffx3d08xrwujnxqp2ekzy8zm0fc6a4cvtgjf3r9n4m027cpjhavqj6rs69tess87mjgkx3rnfup273pv9tl2pruf66ten8r9rajalq9v02k5slczpqtrtz3ly3x47erjyk7waucxzqhy2522afcgwqt3mrqhq5nrwprq9p4q2n8q8w5qegfjplsy4vt88gwxg403k9d0xxkp7p5lpj6xm30jtwjsjk0zee8l9fe5zmr39tz6g4s5lk5kud7ue0y9ngc9c9sr4k2zh4dypq25xxlzyjd6qzedupctp35f2vexc6puqcfzrrdn47s9rxr89ks2q3gwupc8kgv90frgma2awsrzn9wc9pk6u0f09s9s24cyp047u6y0u7qrm2z6gze932yt3l5mvluartyskq5chxf6kc9tqtcalyd20gj45trftf2tc6a52dftyqxq3jpapu
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-05T07:54:14Z"
  mac: ENC[AES256_GCM,data:l5w/+mWOCQJzn/RlRaHl/SvLea51OK41UDwpbP3BBn5xp5s7djcTvTqbJwL4Gw74J1eeHkoaCt0oG84ZrHdRY9ee+KJ3++nZ2Zkcv+kRmpCQkSPslSUGZdktKmkkbjqeTyxn/dUb3Wz4cTnXnM0exRBPsxkUo7KdixKktQ4mCQ4=,iv:kEDHlwRZhc+BS2cj9+t7miD4Mp993EktcPzSr/L+Szc=,tag:mxlP437LSLDJ+YZTSPwk5Q==,type:str]
  version: 3.13.3
