---
global:
  domain: argocd.kalexlab.xyz

configs:
  params:
    server.insecure: true

  rbac:
    policy.csv: |
      g, infra, role:admin

  repositories:
    homelab:
      url: https://github.com/AlessandroZanatta/homelab-v2
      name: homelab
      type: git

  cm:
    admin.enabled: "false"
    dex.config: |
      connectors:
        - config:
            issuer: https://auth.kalexlab.xyz/application/o/management-argocd/
            clientID: management-argocd
            clientSecret: $oidc-secrets:client-secret
            insecureEnableGroups: true
            scopes:
              - openid
              - profile
              - email
          name: Authentik
          type: oidc
          id: authentik

    kustomize.buildOptions: --enable-helm

    # Ignore VolumeSnapshot and VolumeSnapshotContent resources
    # Previously, pruning of these could fail a backup with Velero
    resource.exclusions: |
      - apiGroups:
          - snapshot.storage.k8s.io
        kinds:
          - VolumeSnapshot
          - VolumeSnapshotContent
        clusters:
          - "*"

# Enable metrics
controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
