---
initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.14.0
    imagePullPolicy: Always
    volumeMounts:
      - mountPath: /target
        name: plugins

metrics:
  enabled: true

  serviceMonitor:
    enabled: true

configuration:
  volumeSnapshotLocation:
    - name: default
      provider: aws

  features: EnableCSI
