---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: ddns-updater-secrets
    namespace: ddns-updater
spec:
    secretTemplates:
        - name: ddns-updater-secrets
          stringData:
            config.json: ENC[AES256_GCM,data:t6ChCTNn6tY7RvQ1UvxuUTgWFpp77cPxl9gRPaBTTAX09ZxZprIFfJFL6KEINTyauuVlowVan2aJ6ErG8z8s68yIIFco8DvHkzkl+GctYzkEoFcgy7EkKtun7q1X9xYj+6z1XPyXmnT8PGLmj3f7NJCpnSeu21tIAPMI57tMBjLSwhyF+DCZrXJ2osfguKECwx1GyzKb9MDKmAF99AI96G63etHpU97Og7HgjhB2rTHkm4kLZKI6LgT19ERZOu7uB49az5fF9TOIEjcWHPw57spqU02NO/MDwde9dVyw0NSDlIDxb2YU2NIpmU8h7/oVDZUXYPW7JHzsPV0q7anwVzTFPM1kJ46QrVVmnUikd3V7kgX4NXJ2ZVdKEhGIdpLiKMOyPC2YFIyoG5CAjx4/0H3P08jc0R2/v9z4V+3C8y51KLIBQ13uostyL1U6QddpM7j0nvqlHeed9cWAl6i+duMPmps=,iv:YnNV1VR+sdITWQF3OY/6UB9whfi2jDFwOF2q0DHfBnw=,tag:gGeyPbN0Y6wCP0K1zebM8A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4UzR1cTlXOW1zUnp3TTNV
            QWJySlROMmpnZ3pGMEEzbW5kazEzNXBib0JNCkJNejlMNm1MOVZoN0w1aGJOV0lL
            ZWZaQVF3V0Z6S0MwczBWZ1VBVWRhcFkKLS0tIEU5NVFkSzVrSEFDREpHWFM1Z2xa
            bHBTY3RBWm1jK1RIeXRYaUJiL1BqY3MKZTI9u8gR77PmxxJhxigQwLIeYrtG6g2Q
            QHdxMoTaGSKYP9H4gntl1R6jVd4cyivlwb/q7tTr8QZwTZxdVr7i3Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ff26etr9n8nsp2ve2lkh7w4dqd9g9m9u3y8aw77ureu639mrfatqmuqnhv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-26T17:38:43Z"
    mac: ENC[AES256_GCM,data:LP09QnksYcgl8Xfs4e+mntFjOrmwRzQo68By24F8E4RGmRpAU25zkDf3wVwoGFn8YQyVMOhurwAdAVpMCI8LW67YxabLJdRDfJ/DWTafEuEEHUJCNvMrt66abVqLgXAv5z0BgRF37Y6LKVEqS1HTZ1DSsgag2oxfkZKhd0woRn4=,iv:J73YLnqGhqexKgdlR6swV4f6BQlz7z+7SkKLNvLu/Q4=,tag:EUVJVO7UWqHVqYzrjnu2ow==,type:str]
    version: 3.13.2
