---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik

helmGlobals:
  chartHome: ../../../.charts

helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    version: 41.5.0
    releaseName: traefik
    namespace: traefik
    valuesFile: values/traefik.yaml
    # Fix for the following error when attempting to render this kustomization:
    #   error: Error: execution error at (traefik/templates/servicemonitor.yaml:5:10): ERROR: You have to deploy monitoring.coreos.com/v1 first
    apiVersions:
      - monitoring.coreos.com/v1
      - monitoring.coreos.com/v1/ServiceMonitor

resources:
  - manifests
