---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: velero

helmGlobals:
  chartHome: ../../../.charts

helmCharts:
  - name: velero
    repo: https://vmware-tanzu.github.io/helm-charts/
    version: 12.0.3
    releaseName: velero
    namespace: velero
    valuesFile: values/velero.yaml

resources:
  # External snapshotter
  - https://github.com/kubernetes-csi/external-snapshotter//client/config/crd?ref=v8.6.0
  - https://github.com/kubernetes-csi/external-snapshotter//deploy/kubernetes/snapshot-controller?ref=v8.6.0
  - manifests

patches:
  # This rolebinding needs to be in the kube-system namespace, pointing to the
  # metrics-server service-account in metrics-server namespace
  - target:
      kind: RoleBinding
      name: metrics-server-auth-reader
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: kube-system
      - op: replace
        path: /subjects/0/namespace
        value: velero
