---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: argocd-secrets
  namespace: argocd
spec:
  secretTemplates:
    - name: oidc-secrets
      labels:
        app.kubernetes.io/part-of: argocd
      stringData:
        client-secret: ENC[AES256_GCM,data:jCsbgJbvJEL6Q560shNd4iZjfjXeNTAbWEMkCTC/MOb5cilW3U4hGNwkYJjvAj3vrC9wPayfuluglu6cqL77X9KeAvJMyEW8,iv:Rrl94vg/So0Hpn3NTXN0oC6IDEAtHZjYsm/IQ3hcWVE=,tag:RQKUZvxFoIpeYyjQ2+4s3Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnYVhRTE5WMzdxdWw5T0hR
        NUZZQ2tNQTVrS2g0UmlvYkRuVmVST21IWnhVCnp3elRUZFhiMmMrVllYOWplNFBV
        cWZnWU90SlZxeEpyK1pJY2cvMG9xQ1kKLS0tIFBrZG8vc3BNMWU2Q3RUYkhGVDBw
        Nk1CZjd6UHh1VU9xbzlTb1dFWDRULzgKFT6eb5MmWiOcqowV0Pj8hLsefutfk2ce
        el4PcTlq8kcL+miysQUQfRcpAaziNB9tQDQdc3UeAHd7qIC88eBerQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ff26etr9n8nsp2ve2lkh7w4dqd9g9m9u3y8aw77ureu639mrfatqmuqnhv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-24T18:59:38Z"
  mac: ENC[AES256_GCM,data:iAU8VO6qSIlQOVtYw4YGlt6qtfUGaWxMCx0Jhv2cBEZtPduw4pi9S9h6g9GtDvZgdV9hGB2+U16ozOghfjH9TpiSSk3v3vcO84k7SUS4IXlEBUvCPBd4wlvBFt6fRsEO/RCdVChcRytakbYQxGDlHBu0VQBqRS6j/TwEjG+pFa0=,iv:zUBCk/StLh43xsH9p/5CmJ2/7z3A52LdQMjQZt1NmfM=,tag:OhqFD4J6qRNXTLxsbEH/cg==,type:str]
  version: 3.13.1
