---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: argocd-secrets
  namespace: argocd
spec:
  secretTemplates:
    - name: oidc-secrets
      labels:
        app.kubernetes.io/part-of: argocd
      stringData:
        client-secret: ENC[AES256_GCM,data:Md7wkRMm5Cwu/m1+rSGdNALOiwuuuO0B+zxzdeDfhvM+FYfVlNXec05u9FqtovigPHBs9NN9Tnq8ZI3pCplIOiQAB+WJPPokdTQmT8BMw7PdXKM86uvvb7rK3B+ZIhlq9d8qSAAM53g4k2Ven2tg9rbB6Vnr2IRoQKPTB4g3nLw=,iv:V9YmgXdppPBzUDf11zhovEQrZ1j+cETrb297t0Kzckc=,tag:r+tHnorcGhXqr7YgjBOv1g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZTlQcWxJWEpJWVhxNGNh
        Y2htaTViUkduNTB5aFM5cm9oTmNQZks1Q0U0CnZnaWcwa2szMFN4RlA2RFRVRmlB
        VmEwaVJQUG5jYWk1YWZBL0RJbDg3K28KLS0tIGZVMjlvZDI0QVMyemUyVUdZL2th
        RDc5NXN1Qm93MGc3Z2c4UXB2aVpWbEkKjNYXaB2K+j4lfOoAVcAXsQSnCqwjPpZy
        AwlHGWgGkRrPt7O5BB8nl2vpq+GMD0dWI5mH6FyL3N6IYC8rzXKEcA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ff26etr9n8nsp2ve2lkh7w4dqd9g9m9u3y8aw77ureu639mrfatqmuqnhv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-30T11:40:00Z"
  mac: ENC[AES256_GCM,data:P15h+XlAbwgAcPPPw5jcFeGNiqzxyxydsA1EniSgivTmKJPr+aoR/CsBZ08ujq580CCB0cjx1KukgZzMk6JasEqMV+eEMf2OFgVZYtQblYcsvuNQ38Q3w3EWvxZUUt6StV1Dg1nMMxmChBP9DUTImVjanAgKjnKT+krYefH4ISI=,iv:FQ43sh38/KH/iK5NnDwUcp0GVU/cMjn4RXKioP50c7M=,tag:xgZ0ilXJcqJNygsOkyvAsg==,type:str]
  version: 3.13.3
