---
apiVersion: v1
kind: ConfigMap
metadata:
  name: navidrome-toml-conf
data:
  navidrome.toml: |
    LogLevel = 'INFO'
    MusicFolder = '/music'
    DataFolder = '/data'
    CacheFolder = '/cache'
    BaseUrl = 'https://music.kalexlab.xyz'

    EnableUserEditing = false
    EnableInsightsCollector = false

    [ExtAuth]
    TrustedSources = '10.244.0.0/16'
    UserHeader = "X-authentik-username"
    LogoutURL = "https://auth.kalexlab.xyz/application/o/apps-navidrome/end-session/"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: helper-conf
data:
  MUSIC_DIRECTORY: /music
  BEET_CONFIG_PATH: /config.yaml
  BEET_LIBRARY_PATH: /library/library.db
