---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: music-secrets
  namespace: music
spec:
  secretTemplates:
    - name: navidrome-secrets
      stringData:
        ND_LASTFM_APIKEY: ENC[AES256_GCM,data:3xItzRt4Nipj0SuLV+f0iKcmiKcPmUL1wF5lMCl9OUs=,iv:MA7O5EyJloknALKVFodWnKIjGg56CMd03Nje+k+5DWQ=,tag:PkdP55oa8RK6q7vm3A6RCw==,type:str]
        ND_LASTFM_SECRET: ENC[AES256_GCM,data:rvSoOtn0CFaYONDK8rn5gGgjY2i3fgoDyUtZiziiPLA=,iv:+BjQLwfKHqRvPNy0sM1WWHEl71rcgy0NgL11UH6mLc0=,tag:SXI9YGuj3gSMJdDPaewuiw==,type:str]
    - name: beet-secrets
      stringData:
        config.yaml: ENC[AES256_GCM,data:Oqc6HW3B2aLoBRV2GUEGwKoxIX8Py1+HyT+wbvfeu5IEt2w1SgCfF/Th/94ESoCAhgQK8NU8Alb++BTXENwd3X1YHnFWKXY3l6vg+y/GhXljZaxnu4kZzLMH4KsdfFx9YQ18DDLmglPAWW55v+gvRH+gR/kax+tXhGZKcb8rPPLc0zttSbh7A4icL0jPE3E0oyGQbAaFm4yuqEYizqNWcl/p9BmH2hrSNG0T+dKTwlGVCB+n9kvwCqNWZTC6lM7pgRgVlSmUzi6vszjL884IBtMEsL1HF0I7/m/UeUKtJVgsKJX7lv1g+Hgg1IUr+ifiqfzmghN0S/wrRQ4qTxCd43paLOhEz3RHietFG+hNcfmUeURUBPUTPrBeNG5tZa7sbnWPbo5vwTnPlOa7Jzm/KmUl34e515cnsniaPjRL5qoWnHE2qaGpOMEzRBwoDM8Q57GFTVQknChAyrklsX9vKEEzsdeYHIj+UKm0rzjwsEdK8c52bs/0KOT4fSos6BRTjLV3byQOCW14YzAd,iv:+WnI7AOuNMdqs7qMw2MmLj+s6L/PZ0tA0hPRRSCzWHw=,tag:OVTijF0fhO+zcabmhPqYdw==,type:str]
    - name: registry-credentials
      type: kubernetes.io/dockerconfigjson
      stringData:
        .dockerconfigjson: ENC[AES256_GCM,data:Ugx1iQA6Mnfmn8Pp2AJw0VFU60u7mj/jYaBnY3Os6b7zNqtd72FDaiVlDdK2ZxhAj1/0SewsIh0uqJQga1Xs5MYcAq1bbsWb/mr/fdNft+/j0FtZnufG8xquuMukR4nG/VVhiLtmVnKIbX1M15aXOt8FsIW4a3jWte8fopkm64m4d5ms9bBvnrvpl9ES/hmi4aysXQ9CJ+KHcfx0OR8XnOncz2RwUz70Pidg,iv:Qm3RCo7F1JvaG3VcgCDrj6i3KyqaMUgZyMNm5pRG8pA=,tag:m+smMs4LBC7va5kjV11WGA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLVzBRd3NxYy9ESTRMclhi
        NlpTdHB2Qm52dXhwVm13NUVSWXgrbTNaVUhnClpEUFo3NFgvaTd2ajQ0UjFxZncx
        VjlNWS9RRzNHaW91Zm9HMUs2OGFWUkkKLS0tIHptTTJYSkVQQm1ENU5Ha29vRnVa
        dkNLcGM1VlJid0tzYnEyazRuRG91TDQKbrioHl2DpGMuKANiwqAEM5WR5nASbl9e
        RdRm8i8wyWDg1STJd3HnggLxPQcQe66q64nCPGfObydygcycIHT3Ug==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ff26etr9n8nsp2ve2lkh7w4dqd9g9m9u3y8aw77ureu639mrfatqmuqnhv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-22T06:15:08Z"
  mac: ENC[AES256_GCM,data:BRpCebl0o70Gux0GFfhIUo2/3tDpzv5uqN9oPraywMUru6vyo4scmL4p6SSyUmcstfoEmVokWlBx5ILyss3SqsFNB7BiQmLCD9BbShUuPyNN5I8oajSgS+zckZbhuvVW5bBs+1C5eLPccCY+/vOJx9yI011HUMfLlasJV6dwcTc=,iv:BJU6XsCgVVJtm66acfug13D2OExi8ZCVkoG6O6PWflQ=,tag:FsfiPbxQWQLB5po28z4qZw==,type:str]
  version: 3.13.3
