---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: music-secrets
  namespace: music
spec:
  secretTemplates:
    - name: navidrome-secrets
      stringData:
        ND_LASTFM_APIKEY: ENC[AES256_GCM,data:3gvynsDb3wCCubEzJzRGD4+375fjxET8M1kHT3Mg4PQ=,iv:NRD7rGZQVQYamUFxz6VE5FGfURihUR6QgQzsz8Gw9fw=,tag:iXmt/Qw2FwoXk2SFfIi4Kg==,type:str]
        ND_LASTFM_SECRET: ENC[AES256_GCM,data:KFV+FZDCKxaXXF+Hq2B/65cuHu3F9u9WebfuTSuLE2g=,iv:m/LbQaGvGwbXQwJnhetUm6sG9MX+KGlS6rrzj5ynuKM=,tag:zZMyLd1UaqiY9YEtPsySIQ==,type:str]
    - name: beet-secrets
      stringData:
        config.yaml: ENC[AES256_GCM,data:ahycK1Lh4J2nrGpguKmhqVlcdXna5hydWtDem8J/PurD9oF0Oe5c6KtaAVNv6Uwo7CeHzoa+K+8a1ON//p6/Y2ubDMY0o7pgPp1qfO9e1e4Sk1knJbXr/IPapG4oBxZvJFF5pck0II9p11EcDZIx3fimUBI8gAUgxh9YvfGwSX3xkaBcmhboOJCB2FP80xmL6y0CVhNNe4OVhZmvZ6uyjaIz2x4/Cmpbk28W4Q8VEMR5GiOrFPir5H66LZA5822H1Xt6gOu1qsRiE3ewjNj9YKTgxPnuyCLJ38ddOKzqK9rv9L72NSv5v5mmS+wW0AY8fTEE1EMCYAhwKg+71FERYrdUdqZ8bynqT/vq7BSsJcsW/t9OL0cLjWwq+FaBphQCd7+zgxvFwak4hP0uTU2AnK+G4nt+bc7wZVAfeqLqvdDbUU1Cl9xmayvrHyKwE5G1BKqHIH7Y2KpYLmnFy89zVYeRiKd6II+wN2gSg35LHmml6RrXL4V8Mvr74TGRLeDrNNZlmh8oNg8eGTsL+KfCp6E=,iv:6vowAMWBIaQR1DkUKIJwcx8vWX7zSR30pxMrkL3p/gs=,tag:IUnFN460raoqvQRiedC3tw==,type:str]
    - name: registry-credentials
      type: kubernetes.io/dockerconfigjson
      stringData:
        .dockerconfigjson: ENC[AES256_GCM,data:TDxL+BjUJCSUIkHTfqeY9j3AOqIk8BLZ0KVdJg+MTPs8LEWb0Q33/7UTT/CHKPHkYVPk2V0xOYOJl4cJ/44mTu3ej3GK87R1HBv+/qraU116lZay5WIhIcynfKxlokoH7le4d8S8gG5vrEQ/Ep1YST+DJlFUiN3npDfxNziaLo5yEy00eMJigZj+tKMPDb1yN+0z2Bhewsuorht5Ld55zF/uzUWEEvl5UPol,iv:AGyeTxBqbnwKxHEIpbsVUUjwhHk6V8YzUNw4nSnVIfM=,tag:sqT3T8QQxX57nafmmt2xhg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIN3piaGNMNmxaWFluT1py
        UWpMa3o2emZtK2dGVnptVDNIUVdncVBqQUJBClBsYmFPYUJWeG92cjdvdzllMW1B
        VlRXazhuL09aeWhHRnFSMVNFQmJySnMKLS0tIDJSbkJDT1pBUmN2bzk5MnU3djd1
        NTc2ZXFzTHQzWlVKdFY1TStlL0VRVUkK9Tg3zAfvDcj6LrMfpE/aiM20Dt1W2MYi
        YUKxYT8Zwa8U8XBNnwtlAfgAYTeezja+7ojef7Z56jOfG/XkzeEMNA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ff26etr9n8nsp2ve2lkh7w4dqd9g9m9u3y8aw77ureu639mrfatqmuqnhv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-13T14:08:42Z"
  mac: ENC[AES256_GCM,data:3MDXpSV9T6ceZOI2ZIE2R4D+E95BECh+hyHj4WDz3UltAQ8c0B3JcrJ9nxwlgJy6WNMBgCH+mdr43QQXNv7bJatHNcyYZF8j6+MAJUSS64aDlm6/0jsQLJQQ/5glKqhzYS9youvJqxqYsSpeThNms0jLzm4SlxRgfYsdfNdxy0E=,iv:ej5lnMjyH6tGSPZrdjzWbjj8gInd0QIR/GbVgXTrWSg=,tag:DaRJHGs/TuQI11W01mojfQ==,type:str]
  version: 3.13.2
