---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cnpg-all-clusters
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      kalexlab.xyz/component: cluster
  podMetricsEndpoints:
    - port: metrics
