---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secrets.sops.yaml
  - vsc.yaml
  - trim-job.yaml
  - snapshot-delete-job.yaml
  - s3-bucket.yaml
  - s3-iam.yaml
  - ingress.yaml
  - alerting.yaml
