---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: longhorn-secrets
  namespace: longhorn-system
spec:
  secretTemplates:
    - name: longhorn-s3-credentials
      stringData:
        AWS_ENDPOINTS: ENC[AES256_GCM,data:QVF5+BbRKCe+dZDOYZDlPrVDJ2oHS1JcIhfWiA==,iv:eyzQWJ4o0WJ1NnGVM0KKStgvR9ftlK4W+jT5Lnfmx1k=,tag:0HpPVg1uuPjuo0Fk4BGIsA==,type:str]
        AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Zu8FgsbCLw9zntvqLgIZrn4SEIY=,iv:4k8npH3p6B0z4786RZAmQpGoR6XSiZKTRPoG8laCSpk=,tag:t200Sl4C/M8HQo66vkwLcw==,type:str]
        AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:wM42yxMEux9CCquX39C5U2GH6+JXNMmuLQoCJpeRTVx93vlY57oNrUfF,iv:1xIeKz3ytqyNlBR2NmnYDyIA6r3iH2PuJkamJwSj8ZY=,tag:nEZ+3whFwZpXvqluUEc0Jw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhTW41Zy9PSkYwRUlRNFN5
        MlR2dzZTbkRjZWZjSlQ3c0FmZFJQRUJ5OWpZCmVPN1dpdzlJSnI2amZUUWNVVE11
        ZW9mZ1FMSWl6S2xVRVJhSVgrQXd1NFEKLS0tIGxKV1dtcHNlZWdhcmJWdzJiQ1pR
        NnpSRkpQUEt0NHQvY0xudmswNzdsdHcKQrD9B8ssWNQ4znIVFMK6eLtoY1lRXEq3
        r/zyt3z5Whfrg7meuEJh4NDPlL3tgzxdpFAywhs3Q+b5FiTvPcgN6g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ff26etr9n8nsp2ve2lkh7w4dqd9g9m9u3y8aw77ureu639mrfatqmuqnhv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-06T07:10:20Z"
  mac: ENC[AES256_GCM,data:IHhVtId0Cfkb7RSLnm+b6h3aeLsOcDhmz58PXBZOTMxrM/r1J3A+N5JNj9eS1gkiqu7bg2riMmWMlSoRXfGxYH5o24VofIenRik+vNVzCu+dTw9N0+xL4QKvJ0dt4tK7ynIJGnQXj3qaVxdnTOD9e6RCwhECPRhY1LZOrumaU5E=,iv:3Se4g52+5MfbR1VMs+V71vQVLKVfakh65X3DgUp4tPs=,tag:/9gmPAYrhfMrKSw023ftlw==,type:str]
  version: 3.13.3
