---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: trivy-system

helmGlobals:
  chartHome: ../../../.charts

helmCharts:
  - name: trivy-operator
    repo: https://aquasecurity.github.io/helm-charts/
    version: 0.34.0
    releaseName: trivy
    namespace: trivy-system
    valuesFile: values/trivy-operator.yaml

resources:
  - manifests
