---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  namespace: tasks
  name: kaneo-secrets
spec:
  secretTemplates:
    - name: kaneo-secrets
      stringData:
        AUTH_SECRET: ENC[AES256_GCM,data:E6Ct8PZn3dH9fMXFpaTrbvpSEqwmq74SFyVo+NNtZXBy+VagcxBMiurS/9nCK1MvDf/2ZjL8JhR+aFsJD9ZF7A==,iv:jIcNyKSyu1Uh1VX5acflAtr5ZvwMg26fG329tqEkYkc=,tag:z07cinlExAcFdCxvU1wd0Q==,type:str]
        CUSTOM_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:lSNEFkEh6IOMDoRfSttlTbEeAN0f3wOYvjny5uGRKNEDtqHtA//XAGhJE/AIXWqyCJnpPR7tYnYJgyCAp6gacS+3mUx35aEoad8z7KFQ18391l8pRnMclQL9J1A1YvtdfOEnvSkDRQ1ReEOnW0URwoFRqXcXDbJhVxvENXq73Ug=,iv:HhzK0rPr7jt2YIpi+HYoSZshyHllmaW5CmZ57aBaXxA=,tag:+y2+L9XNQuA7GpG70rW2dA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBa3BYM2tMeVdlOHNLWG9W
        SXVVdElzZnMvaE85NFVtYUJhL2JBcWY3dkd3CnUyT1V2ZHUrOTdNK0hjeFFjYVZs
        bXlpSkt5VGk0bmhBQjgyeDRsQ2ozU00KLS0tIG9BVFl5NWVBQXFhRW1IUGpWOExo
        MGptTFk1VENnWXdiL1g3SWp1aFBYZHMK+RU/LyUTaHPoCRjGHt5oukg2suJsOyTl
        2k5fKBfab0Z+JpBk/H9WRJpA5FczfaTtzZuWrVoLsHBEE2Tq8RQgsw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ff26etr9n8nsp2ve2lkh7w4dqd9g9m9u3y8aw77ureu639mrfatqmuqnhv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-30T11:24:18Z"
  mac: ENC[AES256_GCM,data:UxUcoqKR2igrY/3NMwX3M0+mcEW0T68x+WUjwzxO43Ow1J5l68UxMptBKJPuBPHND0XYR5Vt8paIzR6BH5d5wgeOQWQYT05mnHvdzAeOBxlXps1ZZKKzaiyTaoktXIJ8eQwbbzSWt6M7YGdJTSn9ag+4SfoD347FIzCWVsadMeQ=,iv:MAdR/5kJBnnOef3r2Nx8xcEfREAbTTt9dwyM2MxiAaU=,tag:4rZIKWdxLgArTuYSmNJ55Q==,type:str]
  version: 3.13.3
