---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  namespace: tasks
  name: kaneo-secrets
spec:
  secretTemplates:
    - name: kaneo-secrets
      stringData:
        AUTH_SECRET: ENC[AES256_GCM,data:9aY96GNDRYXiryLAhgzjXVE2WNBjkGmhnH7BPKIcJZrTqdFw4gXGq6R6cM/PVZMIHesfIiLRYH8AMgSydIa9yg==,iv:uDYPK/wseNTtufKVkGVDmSVjJWrmGoqRUm9Q/wobzlk=,tag:koHNhAZU1JEP9G5uIvJ4Zg==,type:str]
        CUSTOM_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:Vv2uNZuYA06Cdb0yU7PWtHVHEJRxfr/rjiFj1kJxWfdn3Y5AuVZqfuqHxJWhpOPZwpeaYC8VrkbGqwowDsaXJD9dY7xoWIFG,iv:6QHcTdC3Rjr9zUwoaC0ho4jVQ8ViesSSd8GXC8vnVME=,tag:UgqEbp3gVW69e6RrmU3PYg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bHNnWGF4TjhSRUpNNjBy
        Y05VV2JQTWpXRHF5bFBIZkJKTHhDekgzNWdZCmp1U2FHQnlDNmROL0krRlJySGNI
        ajRacVRSTlFYbE4zVGJWRGJCdHpEczgKLS0tIE5PcHlMeWlEVjNYZDJ2elhzbkgz
        N1V5Y0VwdlAvVHFkOE91b3p0RUl4d00KUSe8aZxf7p2QBZ28N+TA/qyn1CEYnq4p
        JHcFjfDMQZe8ZJVzyjBkUv4yp+aN0cbVSzRx1WaBt1vfCEOAQuoNBg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ff26etr9n8nsp2ve2lkh7w4dqd9g9m9u3y8aw77ureu639mrfatqmuqnhv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-06T10:36:15Z"
  mac: ENC[AES256_GCM,data:Wty6yKaa5repk8MuXPPQ1IDOZtWIcV0GYN4VhNMiEkpEM3+Xd3kRaObRaQHmeaVD1wOJWnltDn/maKIMSuqgREFolDGmhyh7WB3Awfcx9ieEcUm7e7kXMLHaPrQetCWsz9o7Z3tHJXZ9qsjl10ollJUvcQsJtLN/fq/5MV3qbts=,iv:tSsiskynsSxIIs16t+h4YViWy79SaY+VlmXsy1fr38s=,tag:QvO7jz05vSVjnaz3xrdgNA==,type:str]
  version: 3.13.3
